/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiInsight {
  'finding' : string,
  'category' : string,
  'severity' : InsightSeverity,
  'recommendation' : string,
}
export type AlertId = bigint;
export type AnalysisId = bigint;
export type AnalysisStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'failed' : null };
export type AnalysisType = { 'irrigation_coverage' : null } |
  { 'crop_health' : null } |
  { 'disease_spread' : null } |
  { 'grazing_conditions' : null };
export type AnalyticsPeriod = { 'month' : null } |
  { 'quarter' : null } |
  { 'year' : null };
export interface AnimalAnalytics {
  'revenue' : number,
  'count' : bigint,
  'animalType' : string,
}
export interface AnimalListingPublic {
  'id' : ListingId,
  'createdAt' : Timestamp,
  'count' : bigint,
  'isAvailable' : boolean,
  'pricePerHead' : number,
  'description' : string,
  'keeperId' : UserId,
  'updatedAt' : Timestamp,
  'imageUrl' : [] | [string],
  'breed' : [] | [string],
  'inquiryCount' : bigint,
  'animalType' : string,
  'location' : Location,
}
export interface AnimalRecordPublic {
  'id' : bigint,
  'createdAt' : Timestamp,
  'count' : bigint,
  'healthStatus' : { 'sick' : null } |
    { 'healthy' : null } |
    { 'deceased' : null } |
    { 'under_treatment' : null },
  'keeperId' : UserId,
  'notes' : string,
  'breed' : [] | [string],
  'animalType' : string,
}
export type AnnouncementId = bigint;
export type AnnouncementType = { 'emergency' : null } |
  { 'subsidy' : null } |
  { 'opportunity' : null } |
  { 'policy_update' : null } |
  { 'training' : null };
export type AppStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ApplicationStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface AuctionBid {
  'id' : BidId,
  'auctionId' : AuctionId,
  'bidAmount' : bigint,
  'placedAt' : Timestamp,
  'bidderId' : UserId,
  'isWinning' : boolean,
}
export type AuctionId = bigint;
export interface AuctionListing {
  'id' : AuctionId,
  'region' : string,
  'startTime' : Timestamp,
  'status' : AuctionStatus,
  'startingPrice' : bigint,
  'title' : string,
  'endTime' : Timestamp,
  'unit' : string,
  'isAnonymousBidding' : boolean,
  'description' : string,
  'listingType' : AuctionListingType,
  'currentBidderId' : [] | [UserId],
  'quantity' : bigint,
  'sellerId' : UserId,
  'currentBid' : bigint,
  'bidCount' : bigint,
  'images' : Array<string>,
}
export type AuctionListingType = { 'crop' : null } |
  { 'livestock' : null };
export interface AuctionResult {
  'finalPrice' : bigint,
  'completedAt' : [] | [Timestamp],
  'winnerId' : [] | [UserId],
  'auctionId' : AuctionId,
  'sellerAccepted' : [] | [boolean],
}
export type AuctionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'ended' : null };
export interface BIInsight {
  'trend' : BITrend,
  'descriptionEn' : string,
  'descriptionSw' : string,
  'value' : number,
  'unit' : string,
  'recommendationEn' : string,
  'recommendationSw' : string,
  'titleEn' : string,
  'titleSw' : string,
}
export type BIPeriod = { 'quarterly' : null } |
  { 'monthly' : null } |
  { 'weekly' : null };
export interface BIReport {
  'id' : BIReportId,
  'insights' : Array<BIInsight>,
  'period' : BIPeriod,
  'userId' : UserId,
  'generatedAt' : Timestamp,
  'reportType' : BIReportType,
}
export type BIReportId = bigint;
export type BIReportType = { 'profit_forecast' : null } |
  { 'crop_profitability' : null } |
  { 'livestock_profitability' : null } |
  { 'market_opportunity' : null };
export type BITrend = { 'up' : null } |
  { 'down' : null } |
  { 'flat' : null };
export type BidId = bigint;
export interface BookingPublic {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'in_progress' : null } |
    { 'completed' : null } |
    { 'confirmed' : null },
  'clientId' : UserId,
  'createdAt' : Timestamp,
  'notes' : string,
  'serviceId' : bigint,
  'totalPrice' : number,
  'providerId' : UserId,
  'location' : Location,
  'scheduledAt' : Timestamp,
}
export type BoundaryType = { 'other' : null } |
  { 'farm_field' : null } |
  { 'grazing_zone' : null } |
  { 'orchard' : null };
export type BulkBuyId = bigint;
export interface BulkBuyRequest {
  'id' : BulkBuyId,
  'status' : BulkBuyStatus,
  'responses' : Array<BulkBuyResponse>,
  'createdAt' : Timestamp,
  'unit' : string,
  'groupId' : GroupId,
  'targetDate' : Timestamp,
  'itemName' : string,
  'quantity' : number,
  'requesterId' : UserId,
}
export interface BulkBuyResponse {
  'note' : string,
  'quantity' : number,
  'respondedAt' : Timestamp,
  'responderId' : UserId,
}
export type BulkBuyStatus = { 'cancelled' : null } |
  { 'fulfilled' : null } |
  { 'open' : null };
export interface CalendarEvent {
  'id' : CalendarEventId,
  'title' : string,
  'userId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'recurring' : RecurringPattern,
  'time' : [] | [string],
  'completed' : boolean,
  'notes' : [] | [string],
  'recurringEndDate' : [] | [string],
  'eventType' : CalendarEventType,
}
export type CalendarEventId = bigint;
export type CalendarEventType = { 'vetAppointment' : null } |
  { 'vaccination' : null } |
  { 'breeding' : null } |
  { 'marketDay' : null } |
  { 'feeding' : null } |
  { 'soilTesting' : null } |
  { 'healthCheck' : null } |
  { 'fertilizer' : null } |
  { 'deworming' : null } |
  { 'harvest' : null } |
  { 'irrigation' : null } |
  { 'livestockSale' : null } |
  { 'pestControl' : null } |
  { 'planting' : null };
export type CarbonCertId = bigint;
export interface CarbonCertification {
  'id' : CarbonCertId,
  'owner' : Principal,
  'level' : CertificationLevel,
  'awardedAt' : bigint,
  'totalPoints' : bigint,
}
export interface CarbonPractice {
  'id' : CarbonPracticeId,
  'pointsAwarded' : bigint,
  'owner' : Principal,
  'carbonImpactKg' : bigint,
  'description' : string,
  'practiceType' : PracticeType__1,
  'dateLogged' : bigint,
}
export type CarbonPracticeId = bigint;
export type CategoryId = bigint;
export type CertificationLevel = { 'carbonChampion' : null } |
  { 'waterGuardian' : null } |
  { 'soilSteward' : null };
export type ClaimId = bigint;
export type ClaimStatus = { 'filed' : null } |
  { 'underReview' : null } |
  { 'paid' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ClaimType = { 'flood' : null } |
  { 'drought' : null } |
  { 'theft' : null } |
  { 'other' : null } |
  { 'pestDisease' : null };
export type ContentCategory = { 'soil' : null } |
  { 'grazing' : null } |
  { 'pesticide' : null } |
  { 'water' : null } |
  { 'energy' : null };
export type ContentType = { 'tip' : null } |
  { 'article' : null } |
  { 'guide' : null };
export type ContractId = bigint;
export type ContractStatus = { 'active' : null } |
  { 'disputed' : null } |
  { 'completed' : null } |
  { 'pending_acceptance' : null } |
  { 'draft' : null };
export type ContractTemplateType = { 'service_agreement' : null } |
  { 'delivery_agreement' : null } |
  { 'crop_sale' : null };
export type ConversationId = bigint;
export interface ConversationPublic {
  'id' : ConversationId,
  'participants' : Array<UserId>,
  'lastMessageAt' : Timestamp,
  'subject' : [] | [string],
  'lastMessagePreview' : string,
  'createdAt' : Timestamp,
}
export interface Coordinate { 'lat' : number, 'lng' : number }
export type CoverageType = { 'crop' : null } |
  { 'livestock' : null };
export interface CropAnalytics {
  'revenue' : number,
  'quantity' : number,
  'cropType' : string,
}
export interface CropListingPublic {
  'id' : ListingId,
  'farmerId' : UserId,
  'createdAt' : Timestamp,
  'pricePerKg' : number,
  'isAvailable' : boolean,
  'description' : string,
  'updatedAt' : Timestamp,
  'imageUrl' : [] | [string],
  'cropType' : string,
  'inquiryCount' : bigint,
  'location' : Location,
  'quantityKg' : number,
}
export type DiagnosisId = bigint;
export interface DiagnosisRequest {
  'id' : DiagnosisId,
  'imageData' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'imageUrl' : [] | [string],
  'animalId' : [] | [bigint],
  'symptoms' : Array<string>,
  'cropType' : [] | [string],
  'animalType' : [] | [string],
  'location' : [] | [Location],
  'requesterId' : UserId,
  'diagnosisType' : { 'crop' : null } |
    { 'soil' : null } |
    { 'animal' : null },
}
export interface DiagnosisResultPublic {
  'status' : DiagnosisStatus,
  'requestId' : DiagnosisId,
  'reviewNotes' : [] | [string],
  'recommendations' : Array<string>,
  'diagnosis' : string,
  'reviewedBy' : [] | [UserId],
  'recommendedTreatments' : Array<string>,
  'confidencePercent' : bigint,
  'treatments' : Array<string>,
  'confidence' : number,
  'diagnosedAt' : Timestamp,
  'diagnosedBy' : { 'ai' : null } |
    { 'specialist' : UserId },
  'diagnosisId' : DiagnosisId,
  'preventionTips' : Array<string>,
  'possibleDisease' : string,
}
export type DiagnosisStatus = { 'pending_review' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export interface DigitalContract {
  'id' : ContractId,
  'status' : ContractStatus,
  'terms' : string,
  'title' : string,
  'endDate' : Timestamp,
  'counterpartySignedAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'creatorId' : UserId,
  'templateType' : ContractTemplateType,
  'updatedAt' : Timestamp,
  'currency' : string,
  'counterpartyId' : UserId,
  'partiesNames' : string,
  'creatorSignedAt' : [] | [Timestamp],
  'amount' : number,
  'startDate' : Timestamp,
}
export interface DigitalRecord {
  'id' : RecordId,
  'linkedId' : [] | [bigint],
  'title' : string,
  'userId' : UserId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'unit' : [] | [string],
  'description' : string,
  'recordType' : RecordType,
  'category' : [] | [string],
  'amount' : [] | [number],
}
export interface DroneAnalysis {
  'id' : AnalysisId,
  'status' : AnalysisStatus,
  'imageType' : ImageType,
  'analysisDate' : Timestamp,
  'userId' : UserId,
  'aiInsights' : Array<AiInsight>,
  'analysisType' : AnalysisType,
  'imageUrl' : string,
  'overallHealthScore' : [] | [number],
  'farmId' : [] | [bigint],
}
export interface EmergencyContact {
  'region' : string,
  'userName' : string,
  'userRole' : string,
  'userId' : Principal,
  'averageRating' : number,
  'phone' : [] | [string],
  'reviewCount' : bigint,
}
export interface FarmAnalyticsSnapshot {
  'totalLivestockSold' : bigint,
  'endDate' : Timestamp,
  'period' : AnalyticsPeriod,
  'userId' : UserId,
  'generatedAt' : Timestamp,
  'totalCropsHarvested' : number,
  'totalExpenses' : number,
  'totalSalesRevenue' : number,
  'topCrops' : Array<CropAnalytics>,
  'topAnimals' : Array<AnimalAnalytics>,
  'netProfit' : number,
  'startDate' : Timestamp,
}
export interface FarmBenchmark {
  'region' : string,
  'userId' : Principal,
  'regionalAvgOrders' : bigint,
  'orderCount' : bigint,
  'regionalAvgListings' : bigint,
  'listingCount' : bigint,
}
export interface FarmBoundary {
  'id' : FarmBoundaryId,
  'boundaryType' : BoundaryType,
  'areaHectares' : [] | [number],
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'color' : [] | [string],
  'updatedAt' : Timestamp,
  'areaLabel' : [] | [string],
  'coordinates' : Array<Coordinate>,
}
export type FarmBoundaryId = bigint;
export interface FarmRecord {
  'id' : bigint,
  'soilType' : [] | [string],
  'farmerId' : UserId,
  'soilPh' : [] | [number],
  'name' : string,
  'createdAt' : Timestamp,
  'sizeHectares' : number,
  'cropTypes' : Array<string>,
  'location' : Location,
}
export interface FarmingGroup {
  'id' : GroupId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'inviteCode' : string,
  'memberIds' : Array<UserId>,
  'adminId' : UserId,
}
export interface ForecastBasis {
  'weatherScore' : number,
  'historyScore' : number,
  'soilScore' : number,
  'feedingScore' : number,
}
export interface ForecastFilter {
  'userId' : [] | [UserId],
  'forecastType' : [] | [ForecastType],
}
export type ForecastId = bigint;
export interface ForecastRecord {
  'id' : ForecastId,
  'keyDrivers' : Array<string>,
  'predictedValue' : number,
  'title' : string,
  'basedOn' : ForecastBasis,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'unit' : string,
  'sensitivityNote' : string,
  'confidenceScore' : number,
  'monthlyBreakdown' : Array<MonthlyBreakdown>,
  'forecastType' : ForecastType,
  'validUntil' : Timestamp,
}
export type ForecastType = { 'milk_production' : null } |
  { 'crop_yield' : null } |
  { 'egg_production' : null } |
  { 'livestock_weight' : null };
export interface ForumCategoryPublic {
  'id' : CategoryId,
  'postCount' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'descriptionSwahili' : string,
  'nameSwahili' : string,
}
export interface ForumReplyPublic {
  'id' : ReplyId,
  'upvoteCount' : bigint,
  'authorId' : UserId,
  'body' : string,
  'isAccepted' : boolean,
  'createdAt' : Timestamp,
  'authorName' : string,
  'authorRole' : UserRole,
  'topicId' : TopicId,
}
export interface ForumReplyWithUpvotes {
  'id' : bigint,
  'upvoteCount' : bigint,
  'authorId' : UserId,
  'body' : string,
  'isAccepted' : boolean,
  'createdAt' : Timestamp,
  'authorName' : string,
  'authorRole' : UserRole,
  'hasVoted' : boolean,
  'topicId' : bigint,
}
export interface ForumTopicPublic {
  'id' : TopicId,
  'categoryId' : CategoryId,
  'title' : string,
  'authorId' : UserId,
  'body' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'authorName' : string,
  'authorRole' : UserRole,
  'language' : Language,
  'updatedAt' : Timestamp,
  'isResolved' : boolean,
  'viewCount' : bigint,
  'replyCount' : bigint,
}
export interface ForumTopicSummary {
  'id' : TopicId,
  'categoryId' : CategoryId,
  'title' : string,
  'createdAt' : Timestamp,
  'authorName' : string,
  'authorRole' : UserRole,
  'isResolved' : boolean,
  'viewCount' : bigint,
  'replyCount' : bigint,
}
export interface GovtNGOAnnouncement {
  'id' : AnnouncementId,
  'region' : string,
  'attachmentUrl' : [] | [string],
  'contactInfo' : [] | [string],
  'announcementType' : AnnouncementType,
  'endDate' : [] | [Timestamp],
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'bodyEn' : string,
  'bodySw' : string,
  'isActive' : boolean,
  'authorOrganization' : string,
  'titleEn' : string,
  'titleSw' : string,
  'startDate' : Timestamp,
}
export type GroupId = bigint;
export interface GroupListing {
  'id' : GroupListingId,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'groupId' : GroupId,
  'listingIds' : Array<ListingId>,
}
export type GroupListingId = bigint;
export type GroupMemberRole = { 'member' : null } |
  { 'admin' : null };
export interface GroupMembership {
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : GroupMemberRole,
  'groupId' : GroupId,
}
export type ImageType = { 'satellite' : null } |
  { 'drone' : null };
export interface ImprovementSuggestion {
  'id' : InsightSuggestionId,
  'suggestionText' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'category' : string,
}
export interface InputProductPublic {
  'id' : bigint,
  'stockQuantity' : number,
  'name' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'isAvailable' : boolean,
  'description' : string,
  'pricePerUnit' : number,
  'updatedAt' : Timestamp,
  'imageUrl' : [] | [string],
  'category' : { 'other' : null } |
    { 'equipment' : null } |
    { 'feed' : null } |
    { 'seeds' : null } |
    { 'fertilizer' : null } |
    { 'pesticide' : null },
  'sellerId' : UserId,
  'inquiryCount' : bigint,
}
export type InsightSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type InsightSuggestionId = bigint;
export type InsuranceAppId = bigint;
export interface InsuranceApplication {
  'id' : InsuranceAppId,
  'status' : AppStatus,
  'applicant' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'estimatedValue' : bigint,
  'coverageType' : CoverageType,
  'supportingNotes' : string,
}
export interface InsuranceClaim {
  'id' : ClaimId,
  'status' : ClaimStatus,
  'damageDescription' : string,
  'claimant' : Principal,
  'applicationId' : InsuranceAppId,
  'evidenceNotes' : string,
  'createdAt' : bigint,
  'claimType' : ClaimType,
  'estimatedLoss' : bigint,
}
export type InventoryCategory = { 'other' : null } |
  { 'equipment' : null } |
  { 'feed' : null } |
  { 'medicine' : null } |
  { 'seeds' : null } |
  { 'fertilizer' : null };
export type InventoryChangeType = { 'adjustment' : null } |
  { 'restock' : null } |
  { 'usage' : null };
export interface InventoryHistory {
  'itemId' : InventoryItemId,
  'changeType' : InventoryChangeType,
  'note' : string,
  'timestamp' : Timestamp,
  'delta' : number,
}
export interface InventoryItem {
  'id' : InventoryItemId,
  'supplierContact' : [] | [string],
  'lastRestockedAt' : [] | [Timestamp],
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'quantity' : number,
  'category' : InventoryCategory,
  'reorderLevel' : number,
}
export type InventoryItemId = bigint;
export interface IrrigationBasis {
  'soilMoisture' : string,
  'weatherForecast' : string,
  'seasonalCondition' : string,
}
export type IrrigationId = bigint;
export interface IrrigationLog {
  'id' : IrrigationLogId,
  'userId' : UserId,
  'actualWaterUseLiters' : [] | [bigint],
  'recommendationId' : IrrigationId,
  'notes' : [] | [string],
  'followedOn' : Timestamp,
}
export type IrrigationLogId = bigint;
export interface IrrigationRecommendation {
  'id' : IrrigationId,
  'region' : string,
  'basedOn' : IrrigationBasis,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'hasSetReminder' : boolean,
  'reasoning' : string,
  'cropType' : string,
  'estimatedWaterSavingPercent' : bigint,
  'schedule' : IrrigationSchedule,
  'yieldImpactPercent' : bigint,
  'validUntil' : Timestamp,
}
export interface IrrigationSchedule {
  'bestTimeOfDay' : string,
  'durationMinutes' : bigint,
  'frequencyPerWeek' : bigint,
}
export interface JobApplication {
  'id' : JobApplicationId,
  'status' : ApplicationStatus,
  'applicant' : Principal,
  'appliedAt' : bigint,
  'jobId' : JobId,
  'coverNote' : string,
}
export type JobApplicationId = bigint;
export type JobId = bigint;
export interface JobListing {
  'id' : JobId,
  'status' : JobStatus,
  'title' : string,
  'jobType' : JobType,
  'createdAt' : bigint,
  'description' : string,
  'deadline' : bigint,
  'employer' : Principal,
  'requiredSkills' : Array<string>,
  'payRate' : string,
  'location' : string,
}
export type JobStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'filled' : null };
export type JobType = { 'other' : null } |
  { 'transport' : null } |
  { 'harvesting' : null } |
  { 'spraying' : null } |
  { 'livestockCare' : null } |
  { 'planting' : null };
export type Language = { 'swahili' : null } |
  { 'english' : null };
export type ListingId = bigint;
export interface ListingPublic {
  'id' : ListingId,
  'title' : string,
  'imageUrls' : Array<string>,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'unit' : [] | [string],
  'description' : string,
  'isActive' : boolean,
  'listingType' : ListingType,
  'updatedAt' : Timestamp,
  'quantity' : [] | [number],
  'sellerId' : UserId,
  'price' : number,
  'inquiryCount' : bigint,
  'location' : Location,
}
export type ListingType = { 'service' : null } |
  { 'crop' : null } |
  { 'transport' : null } |
  { 'animal' : null } |
  { 'input' : null };
export interface LoanActivitySummary {
  'period' : bigint,
  'generatedAt' : Timestamp,
  'totalExpenses' : number,
  'totalSales' : number,
  'transactionCount' : bigint,
  'recordCount' : bigint,
}
export interface LoanApplication {
  'id' : LoanId,
  'status' : LoanStatus,
  'applicantId' : UserId,
  'createdAt' : Timestamp,
  'durationMonths' : bigint,
  'lenderNotes' : [] | [string],
  'activitySummary' : string,
  'updatedAt' : Timestamp,
  'amount' : number,
  'purpose' : string,
  'repaymentTerms' : string,
}
export type LoanId = bigint;
export type LoanStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'under_review' : null };
export interface Location {
  'region' : string,
  'district' : string,
  'village' : string,
  'coordinates' : [] | [{ 'lat' : number, 'lng' : number }],
}
export interface MarketGap {
  'demandScore' : bigint,
  'category' : string,
  'supplyCount' : bigint,
  'opportunityScore' : bigint,
}
export interface MarketPricePublic {
  'id' : bigint,
  'region' : string,
  'unit' : string,
  'commodityType' : { 'crop' : null } |
    { 'animal' : null } |
    { 'input' : null },
  'pricePerUnit' : number,
  'recordedBy' : UserId,
  'updatedAt' : Timestamp,
  'market' : string,
  'commodity' : string,
}
export interface MarketRecommendation {
  'id' : bigint,
  'action' : { 'buy' : null } |
    { 'hold' : null } |
    { 'sell' : null } |
    { 'wait' : null },
  'createdAt' : Timestamp,
  'targetPrice' : [] | [number],
  'reasoning' : string,
  'targetDate' : [] | [Timestamp],
  'recommendation' : string,
  'commodity' : string,
  'advisorId' : UserId,
}
export type MessageId = bigint;
export interface MessagePublic {
  'id' : MessageId,
  'content' : string,
  'isRead' : boolean,
  'sentAt' : Timestamp,
  'imageUrl' : [] | [string],
  'conversationId' : ConversationId,
  'senderId' : UserId,
}
export interface MonthlyBreakdown { 'month' : string, 'value' : number }
export type NotificationId = bigint;
export type NotificationPriority = { 'normal' : null } |
  { 'high' : null } |
  { 'critical' : null };
export interface NotificationPublic {
  'id' : NotificationId,
  'title' : string,
  'body' : string,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'priority' : NotificationPriority,
  'relatedId' : [] | [bigint],
  'recipientId' : UserId,
}
export type NotificationType = { 'service_request' : null } |
  { 'disease_alert' : null } |
  { 'price_update' : null } |
  { 'low_stock_alert' : null } |
  { 'weather_alert' : null } |
  { 'govt_announcement' : null } |
  { 'contract_pending' : null } |
  { 'loan_status_update' : null } |
  { 'badge_earned' : null } |
  { 'message' : null } |
  { 'order_update' : null } |
  { 'pest_outbreak' : null } |
  { 'group_invite' : null } |
  { 'vaccination_reminder' : null };
export interface OrderChainEntry {
  'status' : string,
  'date' : Timestamp,
  'orderId' : OrderId,
  'buyerId' : UserId,
}
export type OrderId = bigint;
export interface OrderPublic {
  'id' : OrderId,
  'status' : OrderStatus,
  'listingId' : ListingId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : string,
  'buyerId' : UserId,
  'quantity' : number,
  'sellerId' : UserId,
  'totalPrice' : number,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'in_transit' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface OutbreakAlert {
  'id' : AlertId,
  'sentAt' : Timestamp,
  'message' : string,
  'outbreakId' : OutbreakId,
  'recipientId' : UserId,
}
export interface OutbreakFilter {
  'region' : [] | [string],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'outbreakType' : [] | [OutbreakType],
  'activeOnly' : boolean,
}
export type OutbreakId = bigint;
export interface OutbreakRecord {
  'id' : OutbreakId,
  'region' : string,
  'affectedArea' : [] | [string],
  'description' : string,
  'isActive' : boolean,
  'district' : [] | [string],
  'reportedAt' : Timestamp,
  'reporterId' : UserId,
  'diseaseName' : string,
  'severity' : OutbreakSeverity,
  'outbreakType' : OutbreakType,
  'coordinates' : [] | [{ 'lat' : number, 'lng' : number }],
}
export type OutbreakSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type OutbreakType = { 'livestock_infection' : null } |
  { 'drought' : null } |
  { 'crop_disease' : null } |
  { 'pest_invasion' : null };
export type PaymentId = bigint;
export type PaymentMethod = { 'nmb' : null } |
  { 'mpesa' : null } |
  { 'airtel_money' : null } |
  { 'tigo_pesa' : null } |
  { 'cash' : null } |
  { 'crdb' : null };
export interface PaymentPublic {
  'id' : PaymentId,
  'heldAt' : [] | [Timestamp],
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'createdAt' : Timestamp,
  'reference' : string,
  'escrowNote' : [] | [string],
  'orderId' : [] | [OrderId],
  'updatedAt' : Timestamp,
  'currency' : string,
  'releasedAt' : [] | [Timestamp],
  'amount' : number,
  'payeeId' : UserId,
  'payerId' : UserId,
}
export type PaymentStatus = { 'pending' : null } |
  { 'held' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export type PracticeType = { 'other' : null } |
  { 'composting' : null } |
  { 'water_harvesting' : null } |
  { 'crop_rotation' : null } |
  { 'agroforestry' : null } |
  { 'drip_irrigation' : null } |
  { 'integrated_pest_management' : null } |
  { 'organic_fertilizer' : null };
export type PracticeType__1 = { 'sustainableGrazing' : null } |
  { 'treePlanting' : null } |
  { 'soilConservation' : null } |
  { 'composting' : null } |
  { 'ecoPesticide' : null } |
  { 'waterManagement' : null };
export interface PriceTrend {
  'region' : string,
  'trend' : { 'steady' : null } |
    { 'rising' : null } |
    { 'falling' : null },
  'commodity' : string,
  'dataPoints' : Array<[Timestamp, number]>,
}
export interface ProductOrigin {
  'farmName' : string,
  'userId' : UserId,
  'role' : string,
  'location' : Location,
}
export interface ProductTraceability {
  'id' : TraceabilityId,
  'listingId' : ListingId,
  'createdAt' : Timestamp,
  'origin' : ProductOrigin,
  'productionHistory' : Array<TraceabilityEvent>,
  'specialistNotes' : Array<SpecialistNote>,
  'orderChain' : Array<OrderChainEntry>,
  'qrCodeId' : QrCodeId,
}
export type QrCodeId = string;
export interface RatingRecord {
  'id' : bigint,
  'createdAt' : Timestamp,
  'toUserId' : UserId,
  'comment' : [] | [string],
  'fromUserId' : UserId,
  'rating' : bigint,
}
export type RecordId = bigint;
export type RecordType = { 'expense' : null } |
  { 'vaccination' : null } |
  { 'sale' : null } |
  { 'crop_planting' : null } |
  { 'harvest' : null } |
  { 'health_event' : null };
export type RecurringPattern = { 'none' : null } |
  { 'monthly' : null } |
  { 'yearly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type ReplyId = bigint;
export interface ServiceListingPublic {
  'id' : bigint,
  'serviceType' : string,
  'coverageAreas' : Array<string>,
  'equipment' : Array<string>,
  'createdAt' : Timestamp,
  'isAvailable' : boolean,
  'description' : string,
  'priceRange' : { 'max' : number, 'min' : number },
  'updatedAt' : Timestamp,
  'inquiryCount' : bigint,
  'providerId' : UserId,
}
export interface SoilReport {
  'id' : bigint,
  'recommendations' : Array<string>,
  'createdAt' : Timestamp,
  'specialistId' : UserId,
  'texture' : string,
  'phLevel' : number,
  'nutrients' : {
    'potassium' : number,
    'phosphorus' : number,
    'nitrogen' : number,
  },
  'farmId' : bigint,
  'suitableCrops' : Array<string>,
}
export interface SpecialistDiagnosisAttachment {
  'photoUrls' : Array<string>,
  'specialistId' : UserId,
  'notes' : string,
  'attachedAt' : Timestamp,
  'diagnosisId' : string,
}
export interface SpecialistNote {
  'photoUrls' : Array<string>,
  'date' : Timestamp,
  'note' : string,
  'specialistId' : UserId,
  'specialistRole' : string,
}
export interface SustainabilityContent {
  'id' : SustainabilityContentId,
  'title' : string,
  'contentType' : ContentType,
  'createdAt' : Timestamp,
  'bodyEn' : string,
  'bodySw' : string,
  'category' : ContentCategory,
}
export type SustainabilityContentId = bigint;
export interface SustainabilityRecord {
  'id' : SustainabilityRecordId,
  'impactScore' : [] | [number],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'practiceType' : PracticeType,
  'dateImplemented' : Timestamp,
}
export type SustainabilityRecordId = bigint;
export type Timestamp = bigint;
export interface TopSeller {
  'region' : string,
  'seller' : Principal,
  'averageRating' : number,
  'sellerName' : string,
  'salesVolume' : bigint,
  'listingCount' : bigint,
}
export type TopicId = bigint;
export interface TraceabilityEvent {
  'date' : Timestamp,
  'description' : string,
  'performedBy' : UserId,
  'eventType' : string,
}
export type TraceabilityId = bigint;
export type TransportAvailabilityStatus = { 'available' : null } |
  { 'limited' : null } |
  { 'fullyBooked' : null };
export interface TransportBooking {
  'id' : TransportBookingId,
  'status' : TransportBookingStatus,
  'deliveryAddress' : string,
  'ratePerKm' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'totalCost' : number,
  'pickupAddress' : string,
  'distanceKm' : number,
  'selectedTimeSlot' : string,
  'providerId' : UserId,
}
export type TransportBookingId = bigint;
export type TransportBookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface TransportListingPublic {
  'id' : bigint,
  'vehicleType' : string,
  'coverageAreas' : Array<string>,
  'createdAt' : Timestamp,
  'pricePerKm' : number,
  'isAvailable' : boolean,
  'updatedAt' : Timestamp,
  'capacityTons' : number,
  'inquiryCount' : bigint,
  'providerId' : UserId,
}
export interface TransportTimeSlot {
  'slots' : Array<string>,
  'providerId' : UserId,
  'availabilityStatus' : TransportAvailabilityStatus,
}
export interface TreatmentRecordPublic {
  'id' : bigint,
  'completedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'vetId' : UserId,
  'medication' : Array<string>,
  'treatment' : string,
  'diagnosis' : string,
  'animalId' : bigint,
  'notes' : string,
}
export interface TrendingCrop {
  'averagePrice' : bigint,
  'priceGrowthPct' : bigint,
  'category' : string,
  'listingCount' : bigint,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'ratingCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'language' : Language,
  'averageRating' : number,
  'isVerified' : boolean,
  'profilePictureUrl' : [] | [string],
  'phone' : string,
  'location' : Location,
}
export interface UserReputation {
  'region' : string,
  'userName' : string,
  'userRole' : UserRole,
  'reputationScore' : bigint,
  'earnedBadgesWithDates' : Array<[string, bigint]>,
  'userId' : Principal,
  'badges' : Array<string>,
}
export type UserRole = { 'agri_specialist' : null } |
  { 'market_advisor' : null } |
  { 'veterinarian' : null } |
  { 'weather_soil_specialist' : null } |
  { 'transport_provider' : null } |
  { 'input_service_provider' : null } |
  { 'input_seller' : null } |
  { 'buyer' : null } |
  { 'livestock_keeper' : null } |
  { 'farmer' : null };
export interface VaccinationRecord {
  'id' : bigint,
  'vaccineName' : string,
  'keeperId' : UserId,
  'animalId' : bigint,
  'nextDueAt' : [] | [Timestamp],
  'notes' : string,
  'administeredAt' : Timestamp,
  'administeredBy' : [] | [UserId],
}
export interface WeatherData {
  'alert' : [] | [string],
  'temperature' : number,
  'updatedAt' : Timestamp,
  'humidity' : number,
  'rainfallMm' : number,
  'forecast' : string,
  'location' : Location,
}
export interface WeeklyLeaderboardEntry {
  'region' : string,
  'userName' : string,
  'userRole' : string,
  'userId' : Principal,
  'badges' : Array<string>,
  'weeklyScore' : bigint,
}
export interface WorkerProfile {
  'id' : WorkerProfileId,
  'bio' : string,
  'serviceArea' : string,
  'ratingCount' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'availability' : string,
  'rating' : number,
  'skills' : Array<string>,
}
export type WorkerProfileId = bigint;
export interface _SERVICE {
  'acceptDigitalContract' : ActorMethod<[ContractId], boolean>,
  'addAnimal' : ActorMethod<
    [string, [] | [string], bigint],
    AnimalRecordPublic
  >,
  'addAnimalListing' : ActorMethod<
    [string, [] | [string], bigint, number, string, [] | [string], Location],
    AnimalListingPublic
  >,
  'addCropListing' : ActorMethod<
    [string, number, number, string, [] | [string], Location],
    CropListingPublic
  >,
  'addDigitalRecord' : ActorMethod<
    [
      RecordType,
      Timestamp,
      string,
      string,
      [] | [number],
      [] | [string],
      [] | [string],
      [] | [bigint],
    ],
    DigitalRecord
  >,
  'addImprovementSuggestion' : ActorMethod<
    [string, string],
    InsightSuggestionId
  >,
  'addInputProduct' : ActorMethod<
    [
      string,
      { 'other' : null } |
        { 'equipment' : null } |
        { 'feed' : null } |
        { 'seeds' : null } |
        { 'fertilizer' : null } |
        { 'pesticide' : null },
      string,
      number,
      string,
      number,
      [] | [string],
    ],
    InputProductPublic
  >,
  'addInventoryItem' : ActorMethod<
    [string, InventoryCategory, number, string, number, [] | [string]],
    InventoryItem
  >,
  'addMarketPrice' : ActorMethod<
    [
      string,
      { 'crop' : null } |
        { 'animal' : null } |
        { 'input' : null },
      number,
      string,
      string,
      string,
    ],
    MarketPricePublic
  >,
  'addMarketRecommendation' : ActorMethod<
    [
      string,
      string,
      { 'buy' : null } |
        { 'hold' : null } |
        { 'sell' : null } |
        { 'wait' : null },
      [] | [number],
      [] | [Timestamp],
      string,
    ],
    MarketRecommendation
  >,
  'addServiceListing' : ActorMethod<
    [string, string, number, number, Array<string>, Array<string>],
    ServiceListingPublic
  >,
  'addSoilReport' : ActorMethod<
    [bigint, number, number, number, number, string, Array<string>],
    SoilReport
  >,
  'addSpecialistDiagnosisAttachment' : ActorMethod<
    [string, Array<string>, string],
    SpecialistDiagnosisAttachment
  >,
  'addSpecialistNote' : ActorMethod<
    [TraceabilityId, string, Array<string>],
    boolean
  >,
  'addSpecialistProductNote' : ActorMethod<
    [TraceabilityId, string, Array<string>],
    boolean
  >,
  'addSustainabilityContent' : ActorMethod<
    [ContentType, string, string, string, ContentCategory],
    SustainabilityContent
  >,
  'addTraceabilityEvent' : ActorMethod<
    [TraceabilityId, string, string],
    boolean
  >,
  'addTransportListing' : ActorMethod<
    [string, number, number, Array<string>],
    TransportListingPublic
  >,
  'addTreatmentRecord' : ActorMethod<
    [bigint, string, string, Array<string>, string],
    TreatmentRecordPublic
  >,
  'addVaccinationRecord' : ActorMethod<
    [bigint, UserId, string, [] | [Timestamp], string],
    VaccinationRecord
  >,
  'applyForLoan' : ActorMethod<
    [number, string, bigint, string],
    LoanApplication
  >,
  'applyToJob' : ActorMethod<[JobId, string], JobApplicationId>,
  'cancelAuction' : ActorMethod<[AuctionId], boolean>,
  'changePassword' : ActorMethod<[string, string], boolean>,
  'closeAuction' : ActorMethod<
    [AuctionId],
    { 'ok' : AuctionResult } |
      { 'err' : string }
  >,
  'confirmDelivery' : ActorMethod<[PaymentId], boolean>,
  'confirmPayment' : ActorMethod<[PaymentId], boolean>,
  'createAuction' : ActorMethod<
    [
      AuctionListingType,
      string,
      string,
      bigint,
      Timestamp,
      bigint,
      string,
      Array<string>,
      string,
      boolean,
    ],
    AuctionListing
  >,
  'createBulkBuyRequest' : ActorMethod<
    [GroupId, string, number, string, Timestamp],
    BulkBuyRequest
  >,
  'createCalendarEvent' : ActorMethod<
    [
      CalendarEventType,
      string,
      string,
      [] | [string],
      [] | [string],
      RecurringPattern,
      [] | [string],
    ],
    CalendarEvent
  >,
  'createDigitalContract' : ActorMethod<
    [
      UserId,
      ContractTemplateType,
      string,
      string,
      string,
      number,
      string,
      Timestamp,
      Timestamp,
    ],
    DigitalContract
  >,
  'createFarm' : ActorMethod<
    [string, Location, number, Array<string>],
    FarmRecord
  >,
  'createFarmingGroup' : ActorMethod<[string, string], FarmingGroup>,
  'createGroupListing' : ActorMethod<
    [GroupId, Array<ListingId>, string, string],
    GroupListing
  >,
  'createJobListing' : ActorMethod<
    [string, string, JobType, string, string, bigint, Array<string>],
    JobId
  >,
  'createListing' : ActorMethod<
    [
      ListingType,
      string,
      string,
      number,
      [] | [number],
      [] | [string],
      Location,
      Array<string>,
      Array<string>,
    ],
    ListingPublic
  >,
  'createProductTraceability' : ActorMethod<
    [ListingId, string, Location],
    ProductTraceability
  >,
  'createTopic' : ActorMethod<
    [CategoryId, string, string, Array<string>, Language],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createTransportBooking' : ActorMethod<
    [UserId, number, number, string, string, string],
    TransportBooking
  >,
  'createWorkerProfile' : ActorMethod<
    [string, Array<string>, string, string, string],
    WorkerProfileId
  >,
  'deactivateAnnouncement' : ActorMethod<[AnnouncementId], boolean>,
  'deactivateListing' : ActorMethod<[ListingId], boolean>,
  'deactivateOutbreak' : ActorMethod<[OutbreakId], boolean>,
  'deleteCalendarEvent' : ActorMethod<[CalendarEventId], boolean>,
  'deleteDigitalRecord' : ActorMethod<[RecordId], boolean>,
  'deleteFarmBoundary' : ActorMethod<[FarmBoundaryId], boolean>,
  'deleteForecast' : ActorMethod<[ForecastId], boolean>,
  'deleteInputProduct' : ActorMethod<[bigint], boolean>,
  'deleteServiceListing' : ActorMethod<[bigint], boolean>,
  'deleteSustainabilityPractice' : ActorMethod<
    [SustainabilityRecordId],
    boolean
  >,
  'fileInsuranceClaim' : ActorMethod<
    [InsuranceAppId, ClaimType, string, bigint, string],
    ClaimId
  >,
  'generateBIReport' : ActorMethod<[BIReportType, BIPeriod], BIReport>,
  'generateFarmAnalytics' : ActorMethod<
    [AnalyticsPeriod],
    FarmAnalyticsSnapshot
  >,
  'generateForecast' : ActorMethod<
    [ForecastType, string, string, string],
    ForecastRecord
  >,
  'generateIrrigationRecommendation' : ActorMethod<
    [string, string],
    IrrigationRecommendation
  >,
  'getAnalysesByFarm' : ActorMethod<[bigint], Array<DroneAnalysis>>,
  'getAnalysisById' : ActorMethod<[AnalysisId], [] | [DroneAnalysis]>,
  'getAnimalDiagnosisById' : ActorMethod<
    [DiagnosisId],
    [] | [[DiagnosisRequest, [] | [DiagnosisResultPublic]]]
  >,
  'getAnimalListings' : ActorMethod<
    [[] | [UserId]],
    Array<AnimalListingPublic>
  >,
  'getAnnouncement' : ActorMethod<[AnnouncementId], [] | [GovtNGOAnnouncement]>,
  'getAuction' : ActorMethod<[AuctionId], [] | [AuctionListing]>,
  'getAuctionResult' : ActorMethod<[AuctionId], [] | [AuctionResult]>,
  'getAuctions' : ActorMethod<
    [[] | [AuctionStatus], [] | [AuctionListingType], [] | [string]],
    Array<AuctionListing>
  >,
  'getBIReport' : ActorMethod<[BIReportId], [] | [BIReport]>,
  'getBidsForAuction' : ActorMethod<[AuctionId], Array<AuctionBid>>,
  'getCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getCategories' : ActorMethod<[], Array<ForumCategoryPublic>>,
  'getCropListings' : ActorMethod<[[] | [UserId]], Array<CropListingPublic>>,
  'getDiagnosisById' : ActorMethod<
    [DiagnosisId],
    [] | [[DiagnosisRequest, [] | [DiagnosisResultPublic]]]
  >,
  'getDigitalContract' : ActorMethod<[ContractId], [] | [DigitalContract]>,
  'getDigitalRecord' : ActorMethod<[RecordId], [] | [DigitalRecord]>,
  'getEmergencyContacts' : ActorMethod<[string], Array<EmergencyContact>>,
  'getFarmBoundariesForUser' : ActorMethod<[UserId], Array<FarmBoundary>>,
  'getFarmBoundary' : ActorMethod<[FarmBoundaryId], [] | [FarmBoundary]>,
  'getForecast' : ActorMethod<[ForecastId], [] | [ForecastRecord]>,
  'getForecasts' : ActorMethod<[ForecastFilter], Array<ForecastRecord>>,
  'getForumReplyWithUpvotes' : ActorMethod<
    [bigint],
    [] | [ForumReplyWithUpvotes]
  >,
  'getGroup' : ActorMethod<[GroupId], [] | [FarmingGroup]>,
  'getInputProducts' : ActorMethod<[[] | [UserId]], Array<InputProductPublic>>,
  'getInsuranceApplication' : ActorMethod<
    [InsuranceAppId],
    [] | [InsuranceApplication]
  >,
  'getInsuranceClaim' : ActorMethod<[ClaimId], [] | [InsuranceClaim]>,
  'getInventoryHistory' : ActorMethod<
    [InventoryItemId],
    Array<InventoryHistory>
  >,
  'getIrrigationRecommendation' : ActorMethod<
    [IrrigationId],
    [] | [IrrigationRecommendation]
  >,
  'getJob' : ActorMethod<[JobId], [] | [JobListing]>,
  'getLatestFarmAnalytics' : ActorMethod<[], [] | [FarmAnalyticsSnapshot]>,
  'getLatestPrices' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<MarketPricePublic>
  >,
  'getLeaderboard' : ActorMethod<
    [string, [] | [string]],
    Array<UserReputation>
  >,
  'getListingById' : ActorMethod<[ListingId], [] | [ListingPublic]>,
  'getListings' : ActorMethod<
    [
      [] | [ListingType],
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
    ],
    Array<ListingPublic>
  >,
  'getLoanActivitySummary' : ActorMethod<[], LoanActivitySummary>,
  'getLoanApplication' : ActorMethod<[LoanId], [] | [LoanApplication]>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getMarketGaps' : ActorMethod<[bigint], Array<MarketGap>>,
  'getMarketRecommendations' : ActorMethod<
    [[] | [string]],
    Array<MarketRecommendation>
  >,
  'getMessages' : ActorMethod<[ConversationId], Array<MessagePublic>>,
  'getMyAnalyses' : ActorMethod<[], Array<DroneAnalysis>>,
  'getMyAnimalListings' : ActorMethod<[], Array<AnimalListingPublic>>,
  'getMyAnimals' : ActorMethod<[], Array<AnimalRecordPublic>>,
  'getMyAuctions' : ActorMethod<[], Array<AuctionListing>>,
  'getMyBookings' : ActorMethod<[], Array<BookingPublic>>,
  'getMyCarbonCertifications' : ActorMethod<[], Array<CarbonCertification>>,
  'getMyCarbonPoints' : ActorMethod<[], bigint>,
  'getMyConversations' : ActorMethod<[], Array<ConversationPublic>>,
  'getMyCropListings' : ActorMethod<[], Array<CropListingPublic>>,
  'getMyDiagnoses' : ActorMethod<
    [],
    Array<[DiagnosisRequest, [] | [DiagnosisResultPublic]]>
  >,
  'getMyFarmBenchmark' : ActorMethod<[string], FarmBenchmark>,
  'getMyFarms' : ActorMethod<[], Array<FarmRecord>>,
  'getMyForecasts' : ActorMethod<[], Array<ForecastRecord>>,
  'getMyImprovementSuggestions' : ActorMethod<[], Array<ImprovementSuggestion>>,
  'getMyInputProducts' : ActorMethod<[], Array<InputProductPublic>>,
  'getMyIrrigationLogs' : ActorMethod<[], Array<IrrigationLog>>,
  'getMyIrrigationRecommendations' : ActorMethod<
    [],
    Array<IrrigationRecommendation>
  >,
  'getMyListings' : ActorMethod<[], Array<ListingPublic>>,
  'getMyNotifications' : ActorMethod<[boolean], Array<NotificationPublic>>,
  'getMyOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getMyOutbreakAlerts' : ActorMethod<[], Array<OutbreakAlert>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMySales' : ActorMethod<[], Array<OrderPublic>>,
  'getMyServiceListings' : ActorMethod<[], Array<ServiceListingPublic>>,
  'getMyServiceRequests' : ActorMethod<[], Array<BookingPublic>>,
  'getMyTransactions' : ActorMethod<[], Array<PaymentPublic>>,
  'getMyTransportBookings' : ActorMethod<[], Array<TransportBooking>>,
  'getMyWorkerProfile' : ActorMethod<[], [] | [WorkerProfile]>,
  'getOutbreak' : ActorMethod<[OutbreakId], [] | [OutbreakRecord]>,
  'getOutbreaks' : ActorMethod<[OutbreakFilter], Array<OutbreakRecord>>,
  'getPaymentById' : ActorMethod<[PaymentId], [] | [PaymentPublic]>,
  'getPriceTrend' : ActorMethod<[string, string], PriceTrend>,
  'getProductTraceability' : ActorMethod<
    [ListingId],
    [] | [ProductTraceability]
  >,
  'getRecentTopics' : ActorMethod<[bigint], Array<ForumTopicSummary>>,
  'getRepliesByTopic' : ActorMethod<[TopicId], Array<ForumReplyPublic>>,
  'getReplyUpvoteCount' : ActorMethod<[bigint], bigint>,
  'getServiceListings' : ActorMethod<
    [[] | [string]],
    Array<ServiceListingPublic>
  >,
  'getSoilReports' : ActorMethod<[bigint], Array<SoilReport>>,
  'getSpecialistAttachments' : ActorMethod<
    [string],
    Array<SpecialistDiagnosisAttachment>
  >,
  'getTopContributorOfWeek' : ActorMethod<[], [] | [UserReputation]>,
  'getTopSellersByRegion' : ActorMethod<[string, bigint], Array<TopSeller>>,
  'getTopicById' : ActorMethod<[TopicId], [] | [ForumTopicPublic]>,
  'getTopicsByCategory' : ActorMethod<[CategoryId], Array<ForumTopicSummary>>,
  'getTraceabilityByQrCode' : ActorMethod<
    [QrCodeId],
    [] | [ProductTraceability]
  >,
  'getTransportListings' : ActorMethod<
    [[] | [string]],
    Array<TransportListingPublic>
  >,
  'getTransportTimeSlots' : ActorMethod<[UserId], [] | [TransportTimeSlot]>,
  'getTreatmentHistory' : ActorMethod<[bigint], Array<TreatmentRecordPublic>>,
  'getTrendingCrops' : ActorMethod<[bigint], Array<TrendingCrop>>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserCarbonCertifications' : ActorMethod<
    [Principal],
    Array<CarbonCertification>
  >,
  'getUserCarbonPoints' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getUserRating' : ActorMethod<[UserId], number>,
  'getUserRatings' : ActorMethod<[UserId], Array<RatingRecord>>,
  'getUserReputation' : ActorMethod<[Principal], [] | [UserReputation]>,
  'getVaccinationHistory' : ActorMethod<[bigint], Array<VaccinationRecord>>,
  'getWeather' : ActorMethod<[Location], WeatherData>,
  'getWeeklyLeaderboard' : ActorMethod<[string], Array<WeeklyLeaderboardEntry>>,
  'hasUserUpvotedReply' : ActorMethod<[bigint], boolean>,
  'incrementAnimalInquiry' : ActorMethod<[ListingId], boolean>,
  'incrementCropInquiry' : ActorMethod<[ListingId], boolean>,
  'incrementInputInquiry' : ActorMethod<[bigint], boolean>,
  'incrementListingInquiry' : ActorMethod<[ListingId], boolean>,
  'incrementServiceInquiry' : ActorMethod<[bigint], boolean>,
  'initiateEscrowPayment' : ActorMethod<
    [UserId, [] | [OrderId], number, PaymentMethod, [] | [string]],
    PaymentPublic
  >,
  'initiatePayment' : ActorMethod<
    [UserId, [] | [OrderId], number, PaymentMethod],
    PaymentPublic
  >,
  'joinFarmingGroup' : ActorMethod<[string], boolean>,
  'leaveFarmingGroup' : ActorMethod<[GroupId], boolean>,
  'listAnnouncements' : ActorMethod<
    [[] | [string]],
    Array<GovtNGOAnnouncement>
  >,
  'listAnnouncementsByType' : ActorMethod<
    [[] | [string], AnnouncementType],
    Array<GovtNGOAnnouncement>
  >,
  'listApplicationsForJob' : ActorMethod<[JobId], Array<JobApplication>>,
  'listBulkBuyRequests' : ActorMethod<[GroupId], Array<BulkBuyRequest>>,
  'listDigitalRecords' : ActorMethod<[], Array<DigitalRecord>>,
  'listDigitalRecordsByType' : ActorMethod<[RecordType], Array<DigitalRecord>>,
  'listDigitalRecordsByUserId' : ActorMethod<[UserId], Array<DigitalRecord>>,
  'listFarmAnalytics' : ActorMethod<[], Array<FarmAnalyticsSnapshot>>,
  'listFarmBoundaries' : ActorMethod<[], Array<FarmBoundary>>,
  'listGroupListings' : ActorMethod<[GroupId], Array<GroupListing>>,
  'listGroupMembers' : ActorMethod<[GroupId], Array<GroupMembership>>,
  'listInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'listJobs' : ActorMethod<
    [[] | [JobType], [] | [string], [] | [JobStatus]],
    Array<JobListing>
  >,
  'listMyBIReports' : ActorMethod<[], Array<BIReport>>,
  'listMyCarbonPractices' : ActorMethod<[], Array<CarbonPractice>>,
  'listMyContracts' : ActorMethod<[], Array<DigitalContract>>,
  'listMyGroups' : ActorMethod<[], Array<FarmingGroup>>,
  'listMyInsuranceApplications' : ActorMethod<
    [[] | [AppStatus]],
    Array<InsuranceApplication>
  >,
  'listMyInsuranceClaims' : ActorMethod<
    [[] | [ClaimStatus]],
    Array<InsuranceClaim>
  >,
  'listMyJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'listMyLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'listMySustainabilityPractices' : ActorMethod<
    [],
    Array<SustainabilityRecord>
  >,
  'listSpecialists' : ActorMethod<
    [[] | [UserRole], [] | [string], [] | [Location]],
    Array<UserProfilePublic>
  >,
  'listSustainabilityContent' : ActorMethod<
    [[] | [ContentCategory]],
    Array<SustainabilityContent>
  >,
  'listWorkerProfiles' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<WorkerProfile>
  >,
  'logCarbonPractice' : ActorMethod<
    [PracticeType__1, string, bigint, bigint],
    CarbonPracticeId
  >,
  'logIrrigation' : ActorMethod<
    [IrrigationId, Timestamp, [] | [bigint], [] | [string]],
    IrrigationLog
  >,
  'logSustainabilityPractice' : ActorMethod<
    [PracticeType, string, Timestamp, [] | [number]],
    SustainabilityRecord
  >,
  'login' : ActorMethod<[string, string], [] | [UserProfilePublic]>,
  'markAllNotificationsRead' : ActorMethod<[], bigint>,
  'markMessagesRead' : ActorMethod<[ConversationId], bigint>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'markTopicResolved' : ActorMethod<
    [TopicId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'pauseAnimalListing' : ActorMethod<[ListingId], boolean>,
  'pauseCropListing' : ActorMethod<[ListingId], boolean>,
  'pauseInputProduct' : ActorMethod<[bigint], boolean>,
  'pauseListing' : ActorMethod<[ListingId], boolean>,
  'pauseServiceListing' : ActorMethod<[bigint], boolean>,
  'pauseTransportListing' : ActorMethod<[bigint], boolean>,
  'placeBid' : ActorMethod<
    [AuctionId, bigint],
    { 'ok' : AuctionBid } |
      { 'err' : string }
  >,
  'placeOrder' : ActorMethod<
    [ListingId, UserId, number, number, Location, string],
    OrderPublic
  >,
  'publishAnnouncement' : ActorMethod<
    [
      string,
      string,
      AnnouncementType,
      string,
      string,
      string,
      string,
      string,
      Timestamp,
      [] | [Timestamp],
      [] | [string],
      [] | [string],
    ],
    GovtNGOAnnouncement
  >,
  'rateUser' : ActorMethod<[UserId, bigint, [] | [string]], boolean>,
  'registerUser' : ActorMethod<
    [string, string, string, [] | [string], UserRole, Location, string],
    UserProfilePublic
  >,
  'removeAnimalListing' : ActorMethod<[ListingId], boolean>,
  'removeCropListing' : ActorMethod<[ListingId], boolean>,
  'removeGroupMember' : ActorMethod<[GroupId, UserId], boolean>,
  'removeInventoryItem' : ActorMethod<[InventoryItemId], boolean>,
  'replyToTopic' : ActorMethod<
    [TopicId, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'reportOutbreak' : ActorMethod<
    [
      string,
      [] | [string],
      OutbreakType,
      string,
      OutbreakSeverity,
      string,
      [] | [string],
      [] | [{ 'lat' : number, 'lng' : number }],
    ],
    OutbreakRecord
  >,
  'requestBooking' : ActorMethod<
    [UserId, bigint, Timestamp, Location, number, string],
    BookingPublic
  >,
  'requestOtp' : ActorMethod<[string], string>,
  'respondToBulkBuy' : ActorMethod<[BulkBuyId, number, string], boolean>,
  'respondToJobApplication' : ActorMethod<[JobApplicationId, boolean], boolean>,
  'resumeAnimalListing' : ActorMethod<[ListingId], boolean>,
  'resumeCropListing' : ActorMethod<[ListingId], boolean>,
  'resumeInputProduct' : ActorMethod<[bigint], boolean>,
  'resumeListing' : ActorMethod<[ListingId], boolean>,
  'resumeServiceListing' : ActorMethod<[bigint], boolean>,
  'resumeTransportListing' : ActorMethod<[bigint], boolean>,
  'reviewAnimalDiagnosis' : ActorMethod<
    [
      DiagnosisId,
      { 'rejected' : null } |
        { 'confirmed' : null },
      [] | [string],
    ],
    [] | [DiagnosisResultPublic]
  >,
  'reviewCropDiagnosis' : ActorMethod<
    [
      DiagnosisId,
      { 'rejected' : null } |
        { 'confirmed' : null },
      [] | [string],
    ],
    [] | [DiagnosisResultPublic]
  >,
  'saveFarmBoundary' : ActorMethod<
    [
      string,
      BoundaryType,
      Array<Coordinate>,
      [] | [number],
      [] | [string],
      [] | [string],
    ],
    FarmBoundary
  >,
  'sendMessage' : ActorMethod<
    [ConversationId, string, [] | [string]],
    MessagePublic
  >,
  'sendOutbreakAlert' : ActorMethod<
    [OutbreakId, UserId, string],
    OutbreakAlert
  >,
  'setIrrigationReminder' : ActorMethod<[IrrigationId], boolean>,
  'setTransportTimeSlots' : ActorMethod<
    [Array<string>, TransportAvailabilityStatus],
    undefined
  >,
  'setupFarmerProfile' : ActorMethod<
    [number, Array<string>, [] | [string]],
    boolean
  >,
  'setupLivestockProfile' : ActorMethod<[Array<string>, bigint], boolean>,
  'signDigitalContract' : ActorMethod<[ContractId], boolean>,
  'startConversation' : ActorMethod<
    [UserId, [] | [string], string],
    ConversationPublic
  >,
  'submitAnimalDiagnosis' : ActorMethod<
    [string, [] | [string], Array<string>, [] | [string], [] | [bigint]],
    DiagnosisResultPublic
  >,
  'submitCropDiagnosis' : ActorMethod<
    [string, [] | [string], Array<string>, [] | [string], [] | [Location]],
    DiagnosisResultPublic
  >,
  'submitImageAnalysis' : ActorMethod<
    [[] | [bigint], string, ImageType, AnalysisType],
    DroneAnalysis
  >,
  'submitInsuranceApplication' : ActorMethod<
    [CoverageType, string, bigint, string],
    InsuranceAppId
  >,
  'submitJobRating' : ActorMethod<[JobId, Principal, bigint, string], boolean>,
  'submitSoilAnalysis' : ActorMethod<
    [string, [] | [string]],
    DiagnosisResultPublic
  >,
  'updateAnimalHealth' : ActorMethod<
    [
      bigint,
      { 'sick' : null } |
        { 'healthy' : null } |
        { 'deceased' : null } |
        { 'under_treatment' : null },
      string,
    ],
    boolean
  >,
  'updateAnimalListing' : ActorMethod<
    [ListingId, [] | [bigint], [] | [number], [] | [string], [] | [string]],
    [] | [AnimalListingPublic]
  >,
  'updateBookingStatus' : ActorMethod<
    [
      bigint,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'in_progress' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    boolean
  >,
  'updateCalendarEvent' : ActorMethod<
    [
      CalendarEventId,
      [] | [CalendarEventType],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [RecurringPattern],
      [] | [string],
      [] | [boolean],
    ],
    boolean
  >,
  'updateContractStatus' : ActorMethod<[ContractId, ContractStatus], boolean>,
  'updateCropListing' : ActorMethod<
    [ListingId, [] | [number], [] | [number], [] | [string], [] | [string]],
    [] | [CropListingPublic]
  >,
  'updateDigitalRecord' : ActorMethod<
    [RecordId, string, string, [] | [number]],
    boolean
  >,
  'updateFarmBoundary' : ActorMethod<
    [
      FarmBoundaryId,
      string,
      Array<Coordinate>,
      [] | [number],
      [] | [string],
      [] | [string],
    ],
    boolean
  >,
  'updateInputProduct' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    [] | [InputProductPublic]
  >,
  'updateInsuranceApplicationStatus' : ActorMethod<
    [InsuranceAppId, AppStatus],
    boolean
  >,
  'updateInsuranceClaimStatus' : ActorMethod<[ClaimId, ClaimStatus], boolean>,
  'updateInventoryItem' : ActorMethod<
    [InventoryItemId, number, InventoryChangeType, string],
    boolean
  >,
  'updateJobStatus' : ActorMethod<[JobId, JobStatus], boolean>,
  'updateListing' : ActorMethod<
    [
      ListingId,
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [Array<string>],
    ],
    [] | [ListingPublic]
  >,
  'updateLoanStatus' : ActorMethod<
    [LoanId, LoanStatus, [] | [string]],
    boolean
  >,
  'updateMarketPrice' : ActorMethod<[bigint, number], boolean>,
  'updateMyProfile' : ActorMethod<
    [[] | [string], [] | [Location], [] | [Language], [] | [string]],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateServiceListing' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [Array<string>],
      [] | [Array<string>],
    ],
    [] | [ServiceListingPublic]
  >,
  'upvoteReply' : ActorMethod<[bigint], boolean>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];