import type { Language } from "@/types";
import { create } from "zustand";
import { persist } from "zustand/middleware";

export const translations = {
  en: {
    // Nav
    home: "Home",
    messages: "Messages",
    notifications: "Notifications",
    settings: "Settings",
    transport: "Transport",
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    profile: "Profile",
    // Auth
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    email: "Email",
    password: "Password",
    phone: "Phone Number",
    name: "Full Name",
    location: "Location",
    role: "Role",
    forgotPassword: "Forgot Password?",
    loginOtp: "Login with OTP",
    verifyOtp: "Verify OTP",
    sendOtp: "Send OTP",
    registerNow: "Register Now",
    alreadyHaveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    // Roles
    farmer: "Farmer",
    livestock_keeper: "Livestock Keeper",
    agri_specialist: "Agricultural Specialist",
    veterinarian: "Veterinarian",
    input_seller: "Input Seller",
    input_service_provider: "Input Service Provider",
    weather_soil_specialist: "Weather & Soil Specialist",
    market_advisor: "Market Advisor",
    transport_provider: "Transport Provider",
    buyer: "Buyer",
    // Home
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    todaysWeather: "Today's Weather",
    marketPrices: "Market Prices",
    alerts: "Alerts",
    quickActions: "Quick Actions",
    myFarm: "My Farm",
    myAnimals: "My Animals",
    searchPlaceholder: "Search services, specialists, products...",
    viewAll: "View All",
    // Weather
    temperature: "Temperature",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    rainfall: "Rainfall",
    forecast: "Forecast",
    clearSky: "Clear Sky",
    partlyCloudy: "Partly Cloudy",
    rainy: "Rainy",
    sunny: "Sunny",
    // Market
    pricePerKg: "TSh/kg",
    trend: "Trend",
    commodity: "Commodity",
    price: "Price",
    quantity: "Quantity",
    location_label: "Location",
    // Actions
    detectDisease: "Detect Disease",
    takePicture: "Take Picture",
    analyze: "Analyze",
    sendMessage: "Send Message",
    viewProfile: "View Profile",
    orderNow: "Order Now",
    bookService: "Book Service",
    placeOrder: "Place Order",
    confirm: "Confirm",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    // Notifications
    unreadNotifications: "Unread notifications",
    markAllRead: "Mark all as read",
    diseaseAlert: "Disease Alert",
    weatherAlert: "Weather Alert",
    priceUpdate: "Price Update",
    pestOutbreak: "Pest Outbreak",
    serviceRequest: "Service Request",
    vaccinationReminder: "Vaccination Reminder",
    orderUpdate: "Order Update",
    // Settings
    accountSettings: "Account Settings",
    editProfile: "Edit Profile",
    changePassword: "Change Password",
    notificationPreferences: "Notification Preferences",
    language: "Language",
    privacy: "Privacy",
    farmDetails: "Farm Details",
    livestockDetails: "Livestock Details",
    helpSupport: "Help & Support",
    // Stats
    healthScore: "Health Score",
    animalsRegistered: "Animals Registered",
    lastCheck: "Last Check",
    cropsGrowing: "Crops Growing",
    farmArea: "Farm Area",
    activeAlerts: "Active Alerts",
    // Months abbr
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    // AI Advisor
    aiAdvisor: "AI Farm Advisor",
    aiAdvisorLivestock: "AI Livestock Advisor",
    askAdvisor: "Ask Advisor",
    personalizedTips: "Personalized Tips",
    typeQuestion: "Type your question...",
    advisorThinking: "Advisor is thinking...",
    // Profile Picture
    profilePicture: "Profile Picture",
    takePhoto: "Take Photo",
    chooseFromGallery: "Choose from Gallery",
    addPhoto: "Add Photo",
    changePhoto: "Change Photo",
    // Search
    searchProviders: "Find Providers",
    searchSpecialists: "Specialists",
    searchInputSellers: "Input Sellers",
    searchServiceProviders: "Service Providers",
    searchAll: "All",
    searchNoResults: "No providers found matching your search",
    searchClearQuery: "Clear search",
    searchRateProvider: "Rate this Provider",
    searchContact: "Contact Info",
    searchSpecialization: "Specialization",
    searchProducts: "Products Available",
    searchServices: "Services Offered",
    searchResults: "providers found",
    ratingLabel: "Rating",
    contactProvider: "Contact",
    // Diagnosis
    cropDiagnosis: "AI Crop Diagnosis",
    animalDiagnosis: "AI Animal Diagnosis",
    newDiagnosis: "New Diagnosis",
    diagnosisHistory: "Diagnosis History",
    recentDiagnoses: "Recent Diagnoses",
    lastDiagnosis: "Last Diagnosis",
    requestReview: "Request Specialist Review",
    awaitingReview: "Awaiting Review",
    confirmedBySpecialist: "Confirmed by Specialist",
    needsAssessment: "Needs Further Assessment",
    treatmentSteps: "Treatment Steps",
    preventionTips: "Prevention Tips",
    describeSymptoms: "Describe Symptoms",
    commonSymptoms: "Common Symptoms",
    uploadImage: "Upload Image",
    analyzeWithAI: "Analyze with AI",
    analyzing: "Analyzing...",
    confidence: "Confidence",
    likelyCause: "Likely Cause",
    // Specialist review
    pendingCases: "Pending Cases",
    reviewCase: "Review Case",
    confirmDiagnosis: "Confirm Diagnosis",
    rejectDiagnosis: "Reject Diagnosis",
    reviewNotes: "Review Notes",
    addNotes: "Add notes (optional)",
    farmerInfo: "Farmer Information",
    keeperInfo: "Keeper Information",
    // Transport Search
    findTransport: "Find Transport",
    findTransportSub: "Connect with trusted transport providers in Namwala",
    searchByNameOrLocation: "Search by provider name or location...",
    vehicleType: "Vehicle Type",
    allVehicles: "All Vehicles",
    capacityFilter: "Capacity",
    anyCapacity: "Any Capacity",
    under1ton: "Under 1 ton",
    oneToFiveTons: "1 – 5 tons",
    over5tons: "Over 5 tons",
    pricePerKm: "TSh/km",
    coverageAreas: "Coverage Areas",
    bookTransport: "Book Transport",
    message: "Message",
    noProvidersFound: "No providers match your filters",
    bookingRequest: "Booking Request",
    pickupLocation: "Pickup Location",
    deliveryLocation: "Delivery Location",
    scheduledDate: "Scheduled Date",
    estimatedDistance: "Estimated Distance (km)",
    estimatedCost: "Estimated Cost",
    notes: "Additional Notes",
    sendRequest: "Send Request",
    bookingSuccess:
      "Transport request sent! The provider will contact you shortly.",
    myTransportRequests: "My Transport Requests",
    noBookingsYet: "No transport requests yet. Book a provider above.",
    routeSummary: "Route",
    messageProvider: "Message Provider",
    ratingCount: "reviews",
    // Seller Reviews
    sellerReviews: "Seller Reviews",
    ratings: "Ratings",
    reviews: "Reviews",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    yourRating: "Your Rating",
    yourComment: "Your Comment",
    commentPlaceholder: "Share your experience with this seller...",
    reviewSuccess: "Review submitted successfully!",
    averageRating: "Average Rating",
    noReviews: "No reviews yet",
    beFirstReview: "Be the first to review this seller",
    reviewFrom: "Review from",
    loginToReview: "Log in to leave a review",
    reviewsCount: "reviews",
    starRating: "star rating",
    // Misc
    loading: "Loading...",
    error: "Error",
    retry: "Retry",
    noData: "No data available",
    comingSoon: "Coming soon",
    confirmed: "Confirmed",
    pending: "Pending",
    cancelled: "Cancelled",
    healthy: "Healthy",
    sick: "Sick",
    critical: "Critical",
    high: "High",
    normal: "Normal",
    low: "Low",
    // Checkout & Orders
    checkout: "Checkout",
    orderSummary: "Order Summary",
    paymentMethod: "Payment Method",
    orderConfirmation: "Order Confirmed!",
    proceedToPayment: "Proceed to Payment",
    confirmPayment: "Confirm Payment",
    trackOrder: "Track Order",
    myOrders: "My Orders",
    buyNow: "Buy Now",
    unitPrice: "Unit Price",
    subtotal: "Subtotal",
    estimatedDelivery: "Estimated Delivery",
    orderReference: "Order Reference",
    amountPaid: "Amount Paid",
    paymentMethodUsed: "Payment Method Used",
    orderPlacedSuccess: "Your order has been placed successfully!",
    mpesaInstruction:
      "You will receive an SMS prompt on your phone to complete the payment.",
    bankInstruction:
      "Enter your bank reference number below to confirm payment.",
    phoneNumber: "Phone Number (M-Pesa)",
    bankReference: "Bank Reference Number",
    seller: "Seller",
    inTransit: "In Transit",
    delivered: "Delivered",
    rateSeller: "Rate Seller",
    orderDate: "Order Date",
    noOrders: "No orders yet",
    noOrdersDesc: "Start shopping in the marketplace to see your orders here.",
    goToMarketplace: "Go to Marketplace",
    // Inquiry Notifications
    newInquiry: "New Inquiry",
    inquiryNotificationBody: "is interested in your listing. Tap to reply.",
    tapToReply: "Tap to reply",
    viewMessage: "View Message",
    step: "Step",
    of: "of",
    // Map View
    mapView: "Map View",
    listView: "List View",
    listingsCount: "listings",
    selectRegion: "Click a region to filter listings",
    allRegions: "All Regions",
    regionMap: "Tanzania Region Map",
    noListingsInRegion: "No listings in this region",
    filterByRegion: "Filter by Region",
    viewingRegion: "Viewing listings in",
    backToAllRegions: "Back to All Regions",
    // Landing page
    landingBadge: "Tanzania's #1 Agricultural Platform",
    landingTagline: "Smart Farming. Better Harvests. Connected Communities.",
    landingTaglineSw: "Kilimo Bora. Mavuno Mazuri. Jumuiya Iliyounganishwa.",
    landingGetStarted: "Get Started Free",
    landingSignIn: "Sign In",
    landingScrollDown: "Scroll down",
    landingFeaturesBadge: "Platform Features",
    landingFeaturesTitle: "Everything You Need to Farm Smarter",
    landingFeaturesDesc:
      "From AI disease detection to marketplace trading — all the tools modern Tanzanian farmers need in one place.",
    landingHowBadge: "Getting Started",
    landingHowTitle: "How Namwala Works",
    landingHowDesc: "Three simple steps to transform how you farm.",
    landingHowCta: "Create Your Free Account",
    landingRolesBadge: "For Everyone in Agriculture",
    landingRolesTitle: "Built for Every Role in Agriculture",
    landingRolesDesc:
      "Whether you grow, raise, trade, or advise — Namwala has a dedicated experience for you.",
    landingStatsBannerTitle: "Join Thousands of Farmers Across Tanzania",
    landingStatsBannerDesc:
      "A growing community of agricultural professionals transforming how Tanzania feeds itself.",
    landingStatsCta: "Join the Community",
    landingTrustFree: "Free to Join",
    landingTrustFreeDesc:
      "No hidden fees. Create your account and start immediately at no cost.",
    landingTrustTrusted: "Trusted by Farmers",
    landingTrustTrustedDesc:
      "Rated highly by farmers across 50 districts in Tanzania.",
    landingTrustExperts: "Expert Network",
    landingTrustExpertsDesc:
      "Access 500+ verified specialists, vets, and market advisors.",
    landingFooterTagline: "Smart Farming. Better Harvests.",
    landingFooterLangNote: "Available in",
    landingStatFarmers: "Active Farmers",
    landingStatSpecialists: "Certified Specialists",
    landingStatDistricts: "Districts Covered",
    landingStatSatisfaction: "Satisfaction Rate",
    landingFeatureAI: "AI Disease Detection",
    landingFeatureAIDesc:
      "Identify crop and animal diseases instantly with AI-powered photo analysis.",
    landingFeatureMarket: "Live Market Prices",
    landingFeatureMarketDesc:
      "Real-time price updates so you always sell at fair market value.",
    landingFeatureExperts: "Connect with Experts",
    landingFeatureExpertsDesc:
      "Find certified specialists, vets, and advisors near your location.",
    landingFeatureMarketplace: "Marketplace",
    landingFeatureMarketplaceDesc:
      "Buy and sell crops, livestock, inputs, and services directly.",
    landingFeatureTransport: "Transport Booking",
    landingFeatureTransportDesc:
      "Book reliable transport providers for your goods and livestock.",
    landingFeatureWeather: "Weather & Soil Insights",
    landingFeatureWeatherDesc:
      "Local forecasts and soil analysis tailored to your farm location.",
    landingStep1Title: "Create Your Account",
    landingStep1Desc:
      "Register as a farmer, livestock keeper, buyer, or any agricultural role in minutes.",
    landingStep2Title: "Set Up Your Profile",
    landingStep2Desc:
      "Add your farm details, location, crop types, or livestock you manage.",
    landingStep3Title: "Start Farming Smarter",
    landingStep3Desc:
      "Get AI advice, connect with markets, and manage everything in one place.",
    landingNavFeatures: "features",
    landingNavHowItWorks: "how it works",
    landingNavRoles: "roles",
    // Video section (home)
    aboutNamwala: "About Namwala",
    aboutNamwalaDesc:
      "See how Namwala is transforming agriculture across Tanzania.",
    // Predictive Reminders
    predictiveReminders: "Smart Reminders",
    seasonalReminder: "Seasonal Reminder",
    pestAlert: "Pest Alert",
    marketReminder: "Market Update",
    dismiss: "Dismiss",
    snooze: "Snooze",
    remindMeLater: "Remind me later",
    snoozed24h: "Snoozed for 24 hours",
    noActiveReminders: "No active reminders",
    // Transport Map View
    transportMapView: "Map View",
    transportListView: "List View",
    transportProvidersInRegion: "Providers in this region",
    transportNoProvidersInRegion: "No providers in selected region",
    transportSelectRegion: "Select a region to filter providers",
    transportProvidersCount: "providers",
    transportViewingRegion: "Viewing providers in",
    transportBackToAll: "Show all providers",
    // Voice Input
    tapToSpeak: "Tap to speak",
    listening: "Listening...",
    stopRecording: "Stop recording",
    micNotAvailable: "Microphone not available",
    voiceNotSupported: "Voice input not supported in this browser",
    voiceEnabled: "Voice responses on",
    voiceDisabled: "Voice responses off",
    speakingNow: "Speaking...",
    stopSpeaking: "Stop speaking",
    voiceAssistant: "Voice Assistant",
    askOutLoud: "Ask out loud",
    voiceListening: "Listening...",
    voiceProcessing: "Processing...",
    voiceSpeaking: "Speaking...",
    listenToResponse: "Listen to response",
    // Transport Advanced
    costCalculator: "Cost Calculator",
    distanceKm: "Distance (km)",
    ratePerKm: "Rate per km",
    estimatedCostLabel: "Estimated Cost",
    timeSlots: "Available Time Slots",
    selectTimeSlot: "Select a time slot",
    pickupAddress: "Pickup Address",
    deliveryAddress: "Delivery Address",
    bookNow: "Book Now",
    bookingConfirmed: "Booking Confirmed!",
    bookingReference: "Booking Reference",
    myBookings: "My Transport Bookings",
    availability: "Availability",
    availableSlots: "Available",
    limitedSlots: "Limited",
    fullyBooked: "Fully Booked",
    costBreakdown: "Cost Breakdown",
    selectedSlot: "Selected Time Slot",
    noSlotsAvailable: "No time slots available for this provider",
    bookingSuccessDesc:
      "Your transport has been booked. The provider will contact you to confirm.",
    // Specialist Photo Attachments
    specialistPhotos: "Specialist Photos",
    attachPhotos: "Attach Photos",
    capturePhoto: "Capture Photo",
    addPhotoAttachment: "Add Photo Attachment",
    photoAttachments: "Photo Attachments",
    viewSpecialistPhotos: "View Specialist Photos",
    specialistNotes: "Specialist Notes",
    // Calendar
    calendar: "Calendar",
    calendarTitle: "Farm Calendar",
    addEvent: "Add Event",
    editEvent: "Edit Event",
    deleteEvent: "Delete Event",
    eventType: "Event Type",
    eventTypes: "Event Types",
    eventType_planting: "Planting",
    eventType_irrigation: "Irrigation",
    eventType_fertilizer: "Fertilizer",
    eventType_harvest: "Harvest",
    eventType_pestControl: "Pest Control",
    eventType_soilTesting: "Soil Testing",
    eventType_marketDay: "Market Day",
    eventType_vaccination: "Vaccination",
    eventType_feeding: "Feeding",
    eventType_breeding: "Breeding",
    eventType_vetAppointment: "Vet Appointment",
    eventType_healthCheck: "Health Check",
    eventType_deworming: "Deworming",
    eventType_livestockSale: "Livestock Sale",
    recurring: "Recurring",
    recurringPattern: "Repeat Pattern",
    noEvents: "No events for this day. Tap Add Event to create one.",
    upcomingTasks: "Upcoming Tasks",
    today: "Today",
    tomorrow: "Tomorrow",
    thisWeek: "This Week",
    month: "Month",
    year: "Year",
    eventDate: "Date",
    eventTime: "Time",
    // Record Management
    add_record: "Add Record",
    edit_record: "Edit Record",
    record_type: "Record Type",
    record_harvest: "Harvest",
    record_crop_planting: "Crop Planting",
    record_health_event: "Health Event",
    record_vaccination: "Vaccination",
    record_sale: "Sale",
    record_expense: "Expense",
    record_purchase: "Purchase",
    record_breeding: "Breeding",
    record_other: "Other",
    no_records: "No records found",
    add_first_record: "Add your first record to start tracking progress",
    record_date: "Record Date",
    record_title: "Title",
    record_description: "Description",
    record_amount: "Amount (TSh)",
    record_unit: "Unit",
    record_saved: "Record saved successfully",
    record_deleted: "Record deleted",
    my_records: "My Records",
    filter_records: "Filter Records",
    all_records: "All Records",
    records_history: "Records History",
    // Farming Groups
    create_group: "Create Group",
    join_group: "Join Group",
    my_groups: "My Groups",
    group_members: "Group Members",
    bulk_buy: "Bulk Buy",
    bulk_buy_request: "Bulk Buy Request",
    group_listings: "Group Listings",
    invite_code: "Invite Code",
    leave_group: "Leave Group",
    group_name: "Group Name",
    group_description: "Group Description",
    group_admin: "Group Admin",
    no_groups: "You are not in any groups yet",
    create_first_group: "Create or join a group to start cooperating",
    join_with_code: "Join with Invite Code",
    enter_invite_code: "Enter invite code",
    copy_invite_code: "Copy Invite Code",
    code_copied: "Code copied to clipboard",
    members_count: "members",
    group_created: "Group created successfully",
    joined_group: "Joined group successfully",
    left_group: "You have left the group",
    // Loans
    apply_for_loan: "Apply for Loan",
    loan_amount: "Loan Amount (TSh)",
    loan_purpose: "Purpose of Loan",
    loan_duration: "Duration (Months)",
    repayment_terms: "Repayment Terms",
    activity_summary: "Farm Activity Summary",
    loan_status: "Loan Status",
    loan_pending: "Pending Review",
    loan_approved: "Approved",
    loan_rejected: "Rejected",
    loan_disbursed: "Disbursed",
    my_loans: "My Loan Applications",
    no_loans: "No loan applications yet",
    submit_loan: "Submit Application",
    loan_submitted: "Loan application submitted",
    lender_notes: "Lender Notes",
    // Traceability
    product_origin: "Product Origin",
    production_history: "Production History",
    supply_chain: "Supply Chain",
    trace_product: "Trace Product",
    view_full_chain: "View Full Chain",
    qr_scan: "Scan QR Code",
    traceability_id: "Trace ID",
    no_trace_data: "No traceability data available",
    // Inventory
    inventory: "Inventory",
    add_item: "Add Item",
    stock_level: "Stock Level",
    reorder_level: "Reorder Level",
    low_stock: "Low Stock",
    restock: "Restock",
    item_category: "Category",
    inv_seeds: "Seeds",
    inv_fertilizer: "Fertilizer",
    inv_pesticide: "Pesticide",
    inv_feed: "Animal Feed",
    inv_medicine: "Medicine",
    inv_equipment: "Equipment",
    inv_other: "Other",
    no_inventory: "No inventory items yet",
    add_first_item: "Add your first item to track stock",
    supplier_contact: "Supplier Contact",
    last_restocked: "Last Restocked",
    item_saved: "Item saved",
    low_stock_alert: "Low stock alert",
    // Farm Mapping
    farm_map: "Farm Map",
    draw_boundary: "Draw Boundary",
    grazing_zone: "Grazing Zone",
    farm_field: "Farm Field",
    save_boundary: "Save Boundary",
    boundary_saved: "Boundary saved",
    area_hectares: "Area (Hectares)",
    boundary_name: "Boundary Name",
    boundary_type: "Boundary Type",
    no_boundaries: "No farm boundaries mapped yet",
    draw_first_boundary: "Draw your first boundary on the map",
    delete_boundary: "Delete Boundary",
    boundary_deleted: "Boundary deleted",
    // Analytics
    analytics: "Farm Analytics",
    crop_trends: "Crop Production Trends",
    livestock_performance: "Livestock Performance",
    financial_summary: "Financial Summary",
    net_profit: "Net Profit",
    total_sales: "Total Sales",
    total_expenses: "Total Expenses",
    generate_report: "Generate Report",
    report_period: "Report Period",
    period_monthly: "Monthly",
    period_quarterly: "Quarterly",
    period_yearly: "Yearly",
    no_analytics: "No analytics data yet. Add records to generate insights.",
    top_crops: "Top Crops",
    top_animals: "Top Animals",
    // Contracts
    contracts: "Contracts",
    create_contract: "Create Contract",
    contract_template: "Contract Template",
    template_crop_sale: "Crop Sale Agreement",
    template_service: "Service Agreement",
    template_delivery: "Delivery Agreement",
    template_livestock: "Livestock Sale Agreement",
    template_custom: "Custom Agreement",
    sign_contract: "Sign Contract",
    contract_signed: "Contract Signed",
    contract_active: "Active",
    contract_draft: "Draft",
    contract_completed: "Completed",
    contract_disputed: "Disputed",
    contract_cancelled: "Cancelled",
    parties: "Parties",
    contract_terms: "Terms & Conditions",
    contract_amount: "Contract Amount",
    counterparty: "Other Party",
    no_contracts: "No contracts yet",
    contract_created: "Contract created",
    both_signed: "Both parties have signed",
    // Sustainability
    sustainability: "Sustainability",
    log_practice: "Log Practice",
    impact_score: "Impact Score",
    soil_conservation: "Soil Conservation",
    water_management: "Water Management",
    organic_fertilizer: "Organic Fertilizer",
    crop_rotation: "Crop Rotation",
    composting: "Composting",
    learn_more: "Learn More",
    my_practices: "My Practices",
    no_practices: "No sustainability practices logged yet",
    practice_saved: "Practice logged",
    sustainability_tips: "Sustainability Tips",
    // Govt/NGO
    announcements: "Announcements",
    govt_announcement: "Government",
    ngo_announcement: "NGO",
    training_opportunity: "Training",
    subsidy: "Subsidy",
    emergency: "Emergency",
    policy_update: "Policy",
    subscribe_region: "Subscribe to Region",
    filter_by_type: "Filter by Type",
    no_announcements: "No announcements at this time",
    announcement_active: "Active",
    announcement_expired: "Expired",
    // Business Intelligence
    business_intelligence: "Business Intelligence",
    profit_forecast: "Profit Forecast",
    crop_profitability: "Crop Profitability",
    livestock_profitability: "Livestock Profitability",
    market_opportunity: "Market Opportunity",
    expense_analysis: "Expense Analysis",
    view_insights: "View Insights",
    trend_up: "Rising",
    trend_down: "Falling",
    trend_stable: "Stable",
    bi_no_reports: "No reports generated yet",
    bi_generate_first: "Generate your first report to see insights",
    bi_period_30: "Last 30 Days",
    bi_period_90: "Last 90 Days",
    bi_period_6m: "Last 6 Months",
    bi_period_1y: "Last Year",
    eventNotes: "Notes",
    // Forum
    forum: "Forum",
    communityForum: "Community Forum",
    newPost: "New Post",
    createTopic: "Create Topic",
    replyToTopic: "Post Reply",
    reply: "Reply",
    replies: "replies",
    category: "Category",
    categories: "Categories",
    discussions: "discussions",
    trending: "Trending",
    recent: "Recent",
    popular: "Popular",
    filterPosts: "Filter Posts",
    searchPosts: "Search Posts",
    postCreated: "Post created successfully!",
    replyPosted: "Reply posted!",
    startDiscussion: "Start a Discussion",
    newTopic: "New Topic",
    topicTitle: "Topic Title",
    topicBody: "Describe your question or topic...",
    addTags: "Tags (optional, comma-separated)",
    submitPost: "Post",
    cancelPost: "Cancel",
    resolved: "Resolved",
    unresolved: "Mark Unresolved",
    markResolved: "Mark as Resolved",
    acceptAnswer: "Accept Answer",
    acceptedAnswer: "Accepted Answer",
    recentDiscussions: "Recent Discussions",
    allTopics: "All Topics",
    mostReplies: "Most Replies",
    viewTopic: "View Topic",
    noTopicsYet: "No topics in this category yet",
    noRepliesYet: "No replies yet",
    beFirstToReply: "Be the first to reply!",
    postReply: "Post a Reply",
    forumWelcome: "Welcome to the Community Forum",
    forumWelcomeSub:
      "Ask questions, share knowledge, and learn from fellow farmers and specialists.",
    // Reputation badges
    badgeHelpfulExpert: "Helpful Expert",
    badgeTrustedAdvisor: "Trusted Advisor",
    badgeCommunityLeader: "Community Leader",
    upvote: "Upvote",
    upvoted: "Upvoted",
    communityLeaderboard: "Community Leaderboard",
    leaderboard: "Leaderboard",
    leaderboardSub:
      "Top contributors making a difference in the Namwala community",
    leaderboardRegion: "Region",
    leaderboardRole: "Role",
    leaderboardScore: "Score",
    leaderboardAll: "All",
    leaderboardSpecialists: "Specialists",
    leaderboardFarmers: "Farmers",
    leaderboardEmpty: "No results found. Try adjusting the filters.",
    leaderboardAllTime: "All Time",
    leaderboardThisWeek: "This Week",
    leaderboardWeeklyScore: "Weekly Score",
    leaderboardResetsSunday: "Resets every Sunday at midnight UTC",
    leaderboardNoWeeklyActivity:
      "No activity recorded this week in this region",
    leaderboardActiveContributors: "Active Contributors",
    // Top Contributor of the Week
    topContributorTitle: "Top Contributor of the Week",
    topContributorEmpty: "No contributions this week yet — be the first!",
    topContributorScore: "reputation points",
    // Outbreak Map
    outbreakMap: "Disease Outbreak Map",
    reportedOutbreaks: "Reported Outbreaks",
    filterByType: "Filter by Type",
    filterByDate: "Filter by Date",
    outbreakDetails: "Outbreak Details",
    diseaseName: "Disease Name",
    affectedRegion: "Affected Region",
    severity: "Severity",
    reportOutbreak: "Report Outbreak",
    allOutbreaks: "All Outbreaks",
    cropDisease: "Crop Disease",
    livestockInfection: "Livestock Infection",
    pestInvasion: "Pest Invasion",
    drought: "Drought",
    lowSeverity: "Low",
    mediumSeverity: "Medium",
    highSeverity: "High",
    criticalSeverity: "Critical",
    // Auctions
    liveAuctions: "Live Auctions",
    createAuction: "Create Auction",
    placeBid: "Place Bid",
    currentBid: "Current Bid",
    highestBid: "Highest Bid",
    timeRemaining: "Time Remaining",
    bidHistory: "Bid History",
    auctionEnded: "Auction Ended",
    yourBid: "Your Bid",
    minimumBid: "Minimum Bid",
    startingPrice: "Starting Price",
    endTime: "Ends At",
    auctionWinner: "Auction Winner",
    auctionActive: "Active",
    auctionCancelled: "Cancelled",
    auctionCompleted: "Completed",
    anonymousBidding: "Anonymous Bidding",
    fixedPrice: "Fixed Price",
    bidNow: "Bid Now",
    acceptBid: "Accept Bid",
    rejectBid: "Reject Bid",
    auctionCreated: "Auction created successfully!",
    bidPlaced: "Bid placed successfully!",
    // Forecasting
    harvestForecasting: "Harvest & Production Forecasting",
    forecastedYield: "Forecasted Yield",
    confidenceScore: "Confidence Score",
    keyDrivers: "Key Drivers",
    monthlyBreakdown: "Monthly Breakdown",
    sensitivityAnalysis: "Sensitivity Analysis",
    generateForecast: "Generate Forecast",
    cropYield: "Crop Yield",
    milkProduction: "Milk Production",
    eggProduction: "Egg Production",
    livestockWeight: "Livestock Weight Gain",
    validUntil: "Valid Until",
    forecastBasis: "Forecast Based On",
    weatherScore: "Weather",
    soilScore: "Soil Conditions",
    feedingScore: "Feeding Quality",
    historyScore: "Historical Data",
    // Irrigation
    irrigationRecommendations: "Irrigation Recommendations",
    irrigationSchedule: "Irrigation Schedule",
    waterFrequency: "Watering Frequency",
    durationMinutes: "Duration (Minutes)",
    bestTimeOfDay: "Best Time of Day",
    waterSavings: "Estimated Water Savings",
    yieldImpact: "Yield Impact",
    setReminder: "Set Reminder",
    logUsage: "Log Water Usage",
    irrigationHistory: "Irrigation Log",
    soilMoisture: "Soil Moisture",
    weatherForecast: "Weather Forecast",
    seasonalCondition: "Seasonal Condition",
    irrigationReasoning: "Why This Schedule",
    droneAnalysis: "Drone & Satellite Analysis",
    droneImageType: "Image Type",
    droneImageType_drone: "Drone Image",
    droneImageType_satellite: "Satellite Image",
    droneAnalysisType: "Analysis Type",
    droneAnalysisType_crop_health: "Crop Health",
    droneAnalysisType_irrigation_coverage: "Irrigation Coverage",
    droneAnalysisType_grazing_conditions: "Grazing Conditions",
    droneAnalysisType_disease_spread: "Disease Spread",
    droneSubmitAnalysis: "Submit for Analysis",
    droneHealthScore: "Health Score",
    droneAiInsights: "AI Insights",
    dronePastAnalyses: "Past Analyses",
    droneUploadImage: "Upload Image",
    droneSelectFile: "Click to select an image file",
    droneAnalyzing: "Analyzing...",
    droneNoAnalyses: "No analyses yet. Upload an image to get started.",
    droneSeverity_critical: "Critical",
    droneSeverity_high: "High",
    droneSeverity_medium: "Medium",
    droneSeverity_low: "Low",
    droneRecommendation: "Recommendation",
    droneFinding: "Finding",
  },
  sw: {
    // Nav
    home: "Nyumbani",
    messages: "Ujumbe",
    notifications: "Arifa",
    settings: "Mipangilio",
    transport: "Usafiri",
    dashboard: "Dashibodi",
    marketplace: "Soko",
    profile: "Profaili",
    // Auth
    login: "Ingia",
    signup: "Jisajili",
    logout: "Toka",
    email: "Barua pepe",
    password: "Nywila",
    phone: "Nambari ya Simu",
    name: "Jina Kamili",
    location: "Mahali",
    role: "Jukumu",
    forgotPassword: "Umesahau Nywila?",
    loginOtp: "Ingia na OTP",
    verifyOtp: "Thibitisha OTP",
    sendOtp: "Tuma OTP",
    registerNow: "Jisajili Sasa",
    alreadyHaveAccount: "Una akaunti tayari?",
    noAccount: "Huna akaunti?",
    // Roles
    farmer: "Mkulima",
    livestock_keeper: "Mfugaji",
    agri_specialist: "Mtaalamu wa Kilimo",
    veterinarian: "Daktari wa Wanyama",
    input_seller: "Muuzaji wa Pembejeo",
    input_service_provider: "Mtoa Huduma za Kilimo",
    weather_soil_specialist: "Mtaalamu wa Hali ya Hewa",
    market_advisor: "Mshauri wa Soko",
    transport_provider: "Mtoa Huduma za Usafiri",
    buyer: "Mnunuzi",
    // Home
    goodMorning: "Habari Asubuhi",
    goodAfternoon: "Habari Mchana",
    goodEvening: "Habari Jioni",
    todaysWeather: "Hali ya Hewa Leo",
    marketPrices: "Bei za Soko",
    alerts: "Tahadhari",
    quickActions: "Vitendo vya Haraka",
    myFarm: "Shamba Langu",
    myAnimals: "Wanyama Wangu",
    searchPlaceholder: "Tafuta huduma, wataalamu, bidhaa...",
    viewAll: "Ona Zaidi",
    // Weather
    temperature: "Joto",
    humidity: "Unyevu",
    windSpeed: "Kasi ya Upepo",
    rainfall: "Mvua",
    forecast: "Utabiri",
    clearSky: "Anga Tulivu",
    partlyCloudy: "Mawingu Kidogo",
    rainy: "Mvua",
    sunny: "Jua",
    // Market
    pricePerKg: "TSh/kg",
    trend: "Mwelekeo",
    commodity: "Bidhaa",
    price: "Bei",
    quantity: "Kiasi",
    location_label: "Mahali",
    // Actions
    detectDisease: "Gundua Ugonjwa",
    takePicture: "Piga Picha",
    analyze: "Changanua",
    sendMessage: "Tuma Ujumbe",
    viewProfile: "Ona Profaili",
    orderNow: "Agiza Sasa",
    bookService: "Hifadhi Huduma",
    placeOrder: "Weka Agizo",
    confirm: "Thibitisha",
    cancel: "Ghairi",
    save: "Hifadhi",
    edit: "Hariri",
    delete: "Futa",
    // Notifications
    unreadNotifications: "Arifa ambazo haujasoma",
    markAllRead: "Soma zote",
    diseaseAlert: "Tahadhari ya Ugonjwa",
    weatherAlert: "Tahadhari ya Hewa",
    priceUpdate: "Mabadiliko ya Bei",
    pestOutbreak: "Mlipuko wa Wadudu",
    serviceRequest: "Ombi la Huduma",
    vaccinationReminder: "Kumbusho la Chanjo",
    orderUpdate: "Habari za Agizo",
    // Settings
    accountSettings: "Mipangilio ya Akaunti",
    editProfile: "Hariri Profaili",
    changePassword: "Badilisha Nywila",
    notificationPreferences: "Mapendeleo ya Arifa",
    language: "Lugha",
    privacy: "Faragha",
    farmDetails: "Maelezo ya Shamba",
    livestockDetails: "Maelezo ya Mifugo",
    helpSupport: "Msaada",
    // Stats
    healthScore: "Alama ya Afya",
    animalsRegistered: "Wanyama Waliohifadhiwa",
    lastCheck: "Ukaguzi wa Mwisho",
    cropsGrowing: "Mazao Yanayokua",
    farmArea: "Eneo la Shamba",
    activeAlerts: "Tahadhari Zinazotumika",
    // Months abbr
    sun: "Jum",
    mon: "Jtn",
    tue: "Jmm",
    wed: "Aju",
    thu: "Alh",
    fri: "Ijm",
    sat: "Jmz",
    // AI Advisor
    aiAdvisor: "Mshauri wa AI wa Shamba",
    aiAdvisorLivestock: "Mshauri wa AI wa Mifugo",
    askAdvisor: "Uliza Mshauri",
    personalizedTips: "Ushauri wa Kibinafsi",
    typeQuestion: "Andika swali lako...",
    advisorThinking: "Mshauri anafikiria...",
    // Profile Picture
    profilePicture: "Picha ya Profaili",
    takePhoto: "Piga Picha",
    chooseFromGallery: "Chagua kutoka Kwenye Picha",
    addPhoto: "Ongeza Picha",
    changePhoto: "Badilisha Picha",
    // Search
    searchProviders: "Tafuta Watoa Huduma",
    searchSpecialists: "Wataalamu",
    searchInputSellers: "Wauzaji wa Pembejeo",
    searchServiceProviders: "Watoa Huduma",
    searchAll: "Wote",
    searchNoResults: "Hakuna watoa huduma wanaolingana na utafutaji wako",
    searchClearQuery: "Futa utafutaji",
    searchRateProvider: "Weka Ukadiriaji",
    searchContact: "Mawasiliano",
    searchSpecialization: "Utaalamu",
    searchProducts: "Bidhaa Zinazopatikana",
    searchServices: "Huduma Zinazotolewa",
    searchResults: "wamepatikana",
    ratingLabel: "Ukadiriaji",
    contactProvider: "Wasiliana",
    // Diagnosis
    cropDiagnosis: "Uchunguzi wa Mazao wa AI",
    animalDiagnosis: "Uchunguzi wa Afya ya Mnyama",
    newDiagnosis: "Uchunguzi Mpya",
    diagnosisHistory: "Historia ya Uchunguzi",
    recentDiagnoses: "Uchunguzi wa Hivi Karibuni",
    lastDiagnosis: "Uchunguzi wa Mwisho",
    requestReview: "Omba Mtaalamu Akagundua",
    awaitingReview: "Inasubiri Mapitio",
    confirmedBySpecialist: "Imethibitishwa na Mtaalamu",
    needsAssessment: "Inahitaji Uchunguzi Zaidi",
    treatmentSteps: "Hatua za Matibabu",
    preventionTips: "Vidokezo vya Kinga",
    describeSymptoms: "Elezea Dalili",
    commonSymptoms: "Dalili za Kawaida",
    uploadImage: "Pakia Picha",
    analyzeWithAI: "Changanua na AI",
    analyzing: "Inachunguza...",
    confidence: "Uhakika",
    likelyCause: "Sababu Inayowezekana",
    // Specialist review
    pendingCases: "Kesi Zinazongoja",
    reviewCase: "Kagua Kesi",
    confirmDiagnosis: "Thibitisha Utambuzi",
    rejectDiagnosis: "Kataa Utambuzi",
    reviewNotes: "Maelezo ya Mapitio",
    addNotes: "Ongeza maelezo (si lazima)",
    farmerInfo: "Taarifa za Mkulima",
    keeperInfo: "Taarifa za Mfugaji",
    // Transport Search
    findTransport: "Tafuta Usafiri",
    findTransportSub:
      "Unganika na watoa huduma wa usafiri wa kuaminika huko Namwala",
    searchByNameOrLocation: "Tafuta kwa jina la mtoa au mahali...",
    vehicleType: "Aina ya Gari",
    allVehicles: "Magari Yote",
    capacityFilter: "Uwezo",
    anyCapacity: "Uwezo Wowote",
    under1ton: "Chini ya tani 1",
    oneToFiveTons: "Tani 1 – 5",
    over5tons: "Zaidi ya tani 5",
    pricePerKm: "TSh/km",
    coverageAreas: "Maeneo ya Huduma",
    bookTransport: "Weka Ombi la Usafiri",
    message: "Tuma Ujumbe",
    noProvidersFound: "Hakuna watoa wanaofanana na vichujio vyako",
    bookingRequest: "Ombi la Usafiri",
    pickupLocation: "Mahali pa Kuchukua",
    deliveryLocation: "Mahali pa Kupeleka",
    scheduledDate: "Tarehe ya Kupanga",
    estimatedDistance: "Umbali Uliokadiriwa (km)",
    estimatedCost: "Gharama Inayokadiriwa",
    notes: "Maelezo ya Ziada",
    sendRequest: "Tuma Ombi",
    bookingSuccess:
      "Ombi la usafiri limetumwa! Mtoa huduma atakuwasiliana nawe hivi karibuni.",
    myTransportRequests: "Maombi Yangu ya Usafiri",
    noBookingsYet: "Hakuna maombi bado. Weka ombi la mtoa hapo juu.",
    routeSummary: "Njia",
    messageProvider: "Tuma Ujumbe kwa Mtoa",
    ratingCount: "tathmini",
    // Seller Reviews
    sellerReviews: "Tathmini za Muuzaji",
    ratings: "Ukadiriaji",
    reviews: "Maoni",
    writeReview: "Andika Maoni",
    submitReview: "Wasilisha Maoni",
    yourRating: "Ukadiriaji Wako",
    yourComment: "Maoni Yako",
    commentPlaceholder: "Shiriki uzoefu wako na muuzaji huyu...",
    reviewSuccess: "Maoni yamewasilishwa!",
    averageRating: "Ukadiriaji wa Wastani",
    noReviews: "Hakuna maoni bado",
    beFirstReview: "Kuwa wa kwanza kutoa maoni",
    reviewFrom: "Maoni kutoka kwa",
    loginToReview: "Ingia ili kutoa maoni",
    reviewsCount: "maoni",
    starRating: "ukadiriaji wa nyota",
    // Misc
    loading: "Inapakia...",
    error: "Hitilafu",
    retry: "Jaribu Tena",
    noData: "Hakuna data",
    comingSoon: "Inakuja hivi karibuni",
    confirmed: "Imethibitishwa",
    pending: "Inasubiri",
    cancelled: "Imeghairiwa",
    healthy: "Mzima",
    sick: "Mgonjwa",
    critical: "Hatari",
    high: "Juu",
    normal: "Kawaida",
    low: "Chini",
    // Checkout & Orders
    checkout: "Malipo",
    orderSummary: "Muhtasari wa Agizo",
    paymentMethod: "Njia ya Malipo",
    orderConfirmation: "Agizo Limethibitishwa!",
    proceedToPayment: "Endelea na Malipo",
    confirmPayment: "Thibitisha Malipo",
    trackOrder: "Fuatilia Agizo",
    myOrders: "Maagizo Yangu",
    buyNow: "Nunua Sasa",
    unitPrice: "Bei kwa Kitengo",
    subtotal: "Jumla Ndogo",
    estimatedDelivery: "Uwasilishaji wa Tarajiwa",
    orderReference: "Nambari ya Agizo",
    amountPaid: "Kiasi Kilicholipwa",
    paymentMethodUsed: "Njia ya Malipo Iliyotumiwa",
    orderPlacedSuccess: "Agizo lako limewekwa kwa mafanikio!",
    mpesaInstruction:
      "Utapokea ujumbe wa SMS kwenye simu yako kukamilisha malipo.",
    bankInstruction:
      "Ingiza nambari yako ya benki hapa chini kuthibitisha malipo.",
    phoneNumber: "Nambari ya Simu (M-Pesa)",
    bankReference: "Nambari ya Rejeleo ya Benki",
    seller: "Muuzaji",
    inTransit: "Safirishwa",
    delivered: "Imewasilishwa",
    rateSeller: "Kadiria Muuzaji",
    orderDate: "Tarehe ya Agizo",
    noOrders: "Hakuna maagizo bado",
    noOrdersDesc: "Anza kununua sokoni ili uone maagizo yako hapa.",
    goToMarketplace: "Nenda Sokoni",
    // Inquiry Notifications
    newInquiry: "Ombi Jipya",
    inquiryNotificationBody: "anapenda orodha yako. Gusa kujibu.",
    tapToReply: "Gusa kujibu",
    viewMessage: "Ona Ujumbe",
    step: "Hatua",
    of: "ya",
    // Map View
    mapView: "Ramani",
    listView: "Orodha",
    listingsCount: "bidhaa",
    selectRegion: "Bonyeza mkoa kuona bidhaa",
    allRegions: "Mikoa Yote",
    regionMap: "Ramani ya Mikoa ya Tanzania",
    noListingsInRegion: "Hakuna bidhaa katika mkoa huu",
    filterByRegion: "Chuja kwa Mkoa",
    viewingRegion: "Inaonyesha bidhaa za",
    backToAllRegions: "Rudi Mikoa Yote",
    // Landing page
    landingBadge: "Jukwaa Nambari 1 la Kilimo Tanzania",
    landingTagline: "Kilimo Bora. Mavuno Mazuri. Jumuiya Iliyounganishwa.",
    landingTaglineSw: "Smart Farming. Better Harvests. Connected Communities.",
    landingGetStarted: "Anza Bure",
    landingSignIn: "Ingia",
    landingScrollDown: "Tembeza chini",
    landingFeaturesBadge: "Vipengele vya Jukwaa",
    landingFeaturesTitle: "Kila Kitu Unachohitaji Kulima Kwa Akili",
    landingFeaturesDesc:
      "Kutoka kugundua magonjwa kwa AI hadi biashara ya soko — zana zote wazalendo wa Tanzania wa kisasa wanahitaji mahali pamoja.",
    landingHowBadge: "Kuanza",
    landingHowTitle: "Jinsi Namwala Inavyofanya Kazi",
    landingHowDesc: "Hatua tatu rahisi kubadilisha jinsi unavyolima.",
    landingHowCta: "Fungua Akaunti Yako Bure",
    landingRolesBadge: "Kwa Kila Mtu Katika Kilimo",
    landingRolesTitle: "Imejengwa kwa Kila Jukumu Katika Kilimo",
    landingRolesDesc:
      "Iwe unalima, unafuga, unafanya biashara, au unashauri — Namwala ina uzoefu maalum kwako.",
    landingStatsBannerTitle: "Jiunge na Maelfu ya Wakulima Tanzania Nzima",
    landingStatsBannerDesc:
      "Jumuiya inayokua ya wataalamu wa kilimo wanaobadilisha jinsi Tanzania inavyojilisha.",
    landingStatsCta: "Jiunge na Jumuiya",
    landingTrustFree: "Bure Kujiunga",
    landingTrustFreeDesc:
      "Hakuna ada zilizofichwa. Fungua akaunti yako na uanze mara moja bila gharama.",
    landingTrustTrusted: "Inaaminiwa na Wakulima",
    landingTrustTrustedDesc:
      "Imepewa ukadiriaji wa juu na wakulima katika wilaya 50 Tanzania.",
    landingTrustExperts: "Mtandao wa Wataalamu",
    landingTrustExpertsDesc:
      "Pata wataalamu 500+ waliohakikishwa, madaktari wa wanyama, na washauri wa soko.",
    landingFooterTagline: "Kilimo Bora. Mavuno Mazuri.",
    landingFooterLangNote: "Inapatikana kwa",
    landingStatFarmers: "Wakulima Wanaotumia",
    landingStatSpecialists: "Wataalamu Waliohakikishwa",
    landingStatDistricts: "Wilaya Zinazofikiwa",
    landingStatSatisfaction: "Kiwango cha Kuridhika",
    landingFeatureAI: "Kugundua Magonjwa kwa AI",
    landingFeatureAIDesc:
      "Tambua magonjwa ya mazao na wanyama mara moja kwa uchambuzi wa picha wa AI.",
    landingFeatureMarket: "Bei za Soko za Wakati Halisi",
    landingFeatureMarketDesc:
      "Masasisho ya bei ya wakati halisi ili uwe unauza kwa thamani ya soko ya haki daima.",
    landingFeatureExperts: "Unganika na Wataalamu",
    landingFeatureExpertsDesc:
      "Tafuta wataalamu waliohakikishwa, madaktari wa wanyama, na washauri karibu nawe.",
    landingFeatureMarketplace: "Soko",
    landingFeatureMarketplaceDesc:
      "Nunua na uuze mazao, mifugo, pembejeo, na huduma moja kwa moja.",
    landingFeatureTransport: "Kuweka Usafiri",
    landingFeatureTransportDesc:
      "Weka watoa huduma wa usafiri wa kuaminika kwa bidhaa na mifugo yako.",
    landingFeatureWeather: "Maarifa ya Hali ya Hewa na Udongo",
    landingFeatureWeatherDesc:
      "Utabiri wa hali ya hewa wa ndani na uchambuzi wa udongo uliobinafsishwa kwa eneo lako la shamba.",
    landingStep1Title: "Fungua Akaunti Yako",
    landingStep1Desc:
      "Jisajili kama mkulima, mfugaji, mnunuzi, au jukumu lolote la kilimo kwa dakika chache.",
    landingStep2Title: "Weka Profaili Yako",
    landingStep2Desc:
      "Ongeza maelezo ya shamba lako, mahali, aina za mazao, au mifugo unayosimamia.",
    landingStep3Title: "Anza Kulima Kwa Akili",
    landingStep3Desc:
      "Pata ushauri wa AI, unganika na masoko, na usimamie kila kitu mahali pamoja.",
    landingNavFeatures: "vipengele",
    landingNavHowItWorks: "jinsi inavyofanya kazi",
    landingNavRoles: "majukumu",
    // Video section (home)
    aboutNamwala: "Kuhusu Namwala",
    aboutNamwalaDesc:
      "Tazama jinsi Namwala inavyobadilisha kilimo Tanzania nzima.",
    // Predictive Reminders
    predictiveReminders: "Vikumbusho vya Akili",
    seasonalReminder: "Kumbusho la Msimu",
    pestAlert: "Tahadhari ya Wadudu",
    marketReminder: "Habari za Soko",
    dismiss: "Funga",
    snooze: "Subiri Kidogo",
    remindMeLater: "Nikumbushe Baadaye",
    snoozed24h: "Imepewa pumziko kwa masaa 24",
    noActiveReminders: "Hakuna vikumbusho vya sasa",
    // Transport Map View
    transportMapView: "Ramani",
    transportListView: "Orodha",
    transportProvidersInRegion: "Watoa huduma katika mkoa huu",
    transportNoProvidersInRegion: "Hakuna watoa huduma katika mkoa huu",
    transportSelectRegion: "Chagua mkoa kuchuja watoa huduma",
    transportProvidersCount: "watoa huduma",
    transportViewingRegion: "Inaonyesha watoa huduma wa",
    transportBackToAll: "Onyesha watoa wote",
    // Voice Input
    tapToSpeak: "Gusa kuongea",
    listening: "Inasikiliza...",
    stopRecording: "Simamisha kurekodi",
    micNotAvailable: "Kipaza sauti hakipatikani",
    voiceNotSupported: "Uingizaji wa sauti hautumiki kwenye kivinjari hiki",
    voiceEnabled: "Majibu ya sauti yamewashwa",
    voiceDisabled: "Majibu ya sauti yamezimwa",
    speakingNow: "Inasema...",
    stopSpeaking: "Acha kusema",
    voiceAssistant: "Msaidizi wa Sauti",
    askOutLoud: "Uliza kwa sauti",
    voiceListening: "Sikiliza...",
    voiceProcessing: "Inashughulikia...",
    voiceSpeaking: "Inasema...",
    listenToResponse: "Sikiliza jibu",
    // Transport Advanced
    costCalculator: "Kikokotoo cha Gharama",
    distanceKm: "Umbali (km)",
    ratePerKm: "Bei kwa km",
    estimatedCostLabel: "Gharama Inayokadiriwa",
    timeSlots: "Nyakati za Kuchagua",
    selectTimeSlot: "Chagua wakati",
    pickupAddress: "Anwani ya Kuchukua",
    deliveryAddress: "Anwani ya Kupeleka",
    bookNow: "Weka Sasa",
    bookingConfirmed: "Usafiri Umewekwa!",
    bookingReference: "Nambari ya Usafiri",
    myBookings: "Usafiri Wangu Uliowekwa",
    availability: "Upatikanaji",
    availableSlots: "Inapatikana",
    limitedSlots: "Kidogo",
    fullyBooked: "Imejaa",
    costBreakdown: "Muhtasari wa Gharama",
    selectedSlot: "Wakati Uliochaguliwa",
    noSlotsAvailable: "Hakuna nyakati zinazopatikana kwa mtoa huyu",
    bookingSuccessDesc:
      "Usafiri wako umewekwa. Mtoa atakuwasiliana nawe kuthibitisha.",
    // Specialist Photo Attachments
    specialistPhotos: "Picha za Mtaalamu",
    attachPhotos: "Ambatanisha Picha",
    capturePhoto: "Piga Picha",
    addPhotoAttachment: "Ongeza Picha",
    photoAttachments: "Picha Zilizambatanishwa",
    viewSpecialistPhotos: "Ona Picha za Mtaalamu",
    specialistNotes: "Maelezo ya Mtaalamu",
    // Calendar
    calendar: "Kalenda",
    calendarTitle: "Kalenda ya Shamba",
    addEvent: "Ongeza Tukio",
    editEvent: "Hariri Tukio",
    deleteEvent: "Futa Tukio",
    eventType: "Aina ya Tukio",
    eventTypes: "Aina za Matukio",
    eventType_planting: "Kupanda",
    eventType_irrigation: "Umwagiliaji",
    eventType_fertilizer: "Mbolea",
    eventType_harvest: "Mavuno",
    eventType_pestControl: "Udhibiti wa Wadudu",
    eventType_soilTesting: "Kupima Udongo",
    eventType_marketDay: "Siku ya Soko",
    eventType_vaccination: "Chanjo",
    eventType_feeding: "Kulisha",
    eventType_breeding: "Uzazi",
    eventType_vetAppointment: "Miadi ya Daktari",
    eventType_healthCheck: "Ukaguzi wa Afya",
    eventType_deworming: "Dawa ya Minyoo",
    eventType_livestockSale: "Kuuza Mifugo",
    recurring: "Inayorudiwa",
    recurringPattern: "Mpangilio wa Kurudia",
    noEvents: "Hakuna matukio siku hii. Gusa Ongeza Tukio kuunda.",
    upcomingTasks: "Kazi Zijazo",
    today: "Leo",
    tomorrow: "Kesho",
    thisWeek: "Wiki Hii",
    month: "Mwezi",
    year: "Mwaka",
    eventDate: "Tarehe",
    eventTime: "Wakati",
    // Record Management
    add_record: "Ongeza Rekodi",
    edit_record: "Hariri Rekodi",
    record_type: "Aina ya Rekodi",
    record_harvest: "Mavuno",
    record_crop_planting: "Kupanda Mazao",
    record_health_event: "Tukio la Afya",
    record_vaccination: "Chanjo",
    record_sale: "Uuzaji",
    record_expense: "Gharama",
    record_purchase: "Ununuzi",
    record_breeding: "Uzazi",
    record_other: "Nyingine",
    no_records: "Hakuna rekodi zilizopatikana",
    add_first_record:
      "Ongeza rekodi yako ya kwanza kuanza kufuatilia maendeleo",
    record_date: "Tarehe ya Rekodi",
    record_title: "Kichwa",
    record_description: "Maelezo",
    record_amount: "Kiasi (TSh)",
    record_unit: "Kitengo",
    record_saved: "Rekodi imehifadhiwa",
    record_deleted: "Rekodi imefutwa",
    my_records: "Rekodi Zangu",
    filter_records: "Chuja Rekodi",
    all_records: "Rekodi Zote",
    records_history: "Historia ya Rekodi",
    // Farming Groups
    create_group: "Unda Kikundi",
    join_group: "Jiunge na Kikundi",
    my_groups: "Vikundi Vyangu",
    group_members: "Wanakikundi",
    bulk_buy: "Ununuzi wa Pamoja",
    bulk_buy_request: "Ombi la Ununuzi wa Pamoja",
    group_listings: "Orodha za Kikundi",
    invite_code: "Nambari ya Mwaliko",
    leave_group: "Toka Kikundini",
    group_name: "Jina la Kikundi",
    group_description: "Maelezo ya Kikundi",
    group_admin: "Kiongozi wa Kikundi",
    no_groups: "Bado hujajiunga na kikundi chochote",
    create_first_group: "Unda au jiunge na kikundi kuanza kushirikiana",
    join_with_code: "Jiunge na Nambari ya Mwaliko",
    enter_invite_code: "Ingiza nambari ya mwaliko",
    copy_invite_code: "Nakili Nambari ya Mwaliko",
    code_copied: "Nambari imenakiliwa",
    members_count: "wanakikundi",
    group_created: "Kikundi kimeundwa",
    joined_group: "Umejiunga na kikundi",
    left_group: "Umetoka kikundini",
    // Loans
    apply_for_loan: "Omba Mkopo",
    loan_amount: "Kiasi cha Mkopo (TSh)",
    loan_purpose: "Lengo la Mkopo",
    loan_duration: "Muda (Miezi)",
    repayment_terms: "Masharti ya Ulipaji",
    activity_summary: "Muhtasari wa Shughuli za Shamba",
    loan_status: "Hali ya Mkopo",
    loan_pending: "Inasubiri Ukaguzi",
    loan_approved: "Imekubaliwa",
    loan_rejected: "Imekataliwa",
    loan_disbursed: "Imetolewa",
    my_loans: "Maombi Yangu ya Mkopo",
    no_loans: "Hakuna maombi ya mkopo bado",
    submit_loan: "Wasilisha Maombi",
    loan_submitted: "Maombi ya mkopo yamewasilishwa",
    lender_notes: "Maelezo ya Mkopeshaji",
    // Traceability
    product_origin: "Asili ya Bidhaa",
    production_history: "Historia ya Uzalishaji",
    supply_chain: "Mnyororo wa Usambazaji",
    trace_product: "Fuatilia Bidhaa",
    view_full_chain: "Ona Mnyororo Wote",
    qr_scan: "Scan QR Code",
    traceability_id: "Kitambulisho cha Ufuatiliaji",
    no_trace_data: "Hakuna data ya ufuatiliaji",
    // Inventory
    inventory: "Hifadhi",
    add_item: "Ongeza Bidhaa",
    stock_level: "Kiwango cha Hifadhi",
    reorder_level: "Kiwango cha Kuagiza Tena",
    low_stock: "Hifadhi Ndogo",
    restock: "Jaza Hifadhi",
    item_category: "Aina",
    inv_seeds: "Mbegu",
    inv_fertilizer: "Mbolea",
    inv_pesticide: "Dawa ya Wadudu",
    inv_feed: "Chakula cha Wanyama",
    inv_medicine: "Dawa",
    inv_equipment: "Vifaa",
    inv_other: "Nyingine",
    no_inventory: "Hakuna bidhaa za hifadhi bado",
    add_first_item: "Ongeza bidhaa yako ya kwanza kufuatilia hifadhi",
    supplier_contact: "Mawasiliano ya Msambazaji",
    last_restocked: "Imejazwa Mara ya Mwisho",
    item_saved: "Bidhaa imehifadhiwa",
    low_stock_alert: "Tahadhari ya hifadhi ndogo",
    // Farm Mapping
    farm_map: "Ramani ya Shamba",
    draw_boundary: "Chora Mipaka",
    grazing_zone: "Eneo la Malisho",
    farm_field: "Shamba",
    save_boundary: "Hifadhi Mipaka",
    boundary_saved: "Mipaka imehifadhiwa",
    area_hectares: "Eneo (Hekta)",
    boundary_name: "Jina la Eneo",
    boundary_type: "Aina ya Mipaka",
    no_boundaries: "Hakuna mipaka ya shamba bado",
    draw_first_boundary: "Chora mipaka yako ya kwanza kwenye ramani",
    delete_boundary: "Futa Mipaka",
    boundary_deleted: "Mipaka imefutwa",
    // Analytics
    analytics: "Uchambuzi wa Shamba",
    crop_trends: "Mwelekeo wa Mazao",
    livestock_performance: "Utendaji wa Mifugo",
    financial_summary: "Muhtasari wa Fedha",
    net_profit: "Faida Halisi",
    total_sales: "Jumla ya Mauzo",
    total_expenses: "Jumla ya Gharama",
    generate_report: "Tengeneza Ripoti",
    report_period: "Kipindi cha Ripoti",
    period_monthly: "Kila Mwezi",
    period_quarterly: "Kila Robo Mwaka",
    period_yearly: "Kila Mwaka",
    no_analytics:
      "Hakuna data ya uchambuzi bado. Ongeza rekodi kupata maarifa.",
    top_crops: "Mazao Bora",
    top_animals: "Wanyama Bora",
    // Contracts
    contracts: "Mikataba",
    create_contract: "Unda Mkataba",
    contract_template: "Kiolezo cha Mkataba",
    template_crop_sale: "Makubaliano ya Uuzaji Mazao",
    template_service: "Makubaliano ya Huduma",
    template_delivery: "Makubaliano ya Uwasilishaji",
    template_livestock: "Makubaliano ya Uuzaji Mifugo",
    template_custom: "Makubaliano Maalum",
    sign_contract: "Saini Mkataba",
    contract_signed: "Mkataba Umesainiwa",
    contract_active: "Unaotumika",
    contract_draft: "Rasimu",
    contract_completed: "Umekamilika",
    contract_disputed: "Umegombaniwa",
    contract_cancelled: "Umeghairiwa",
    parties: "Wahusika",
    contract_terms: "Masharti na Hali",
    contract_amount: "Kiasi cha Mkataba",
    counterparty: "Mhusika Mwingine",
    no_contracts: "Hakuna mikataba bado",
    contract_created: "Mkataba umeundwa",
    both_signed: "Wahusika wote wamesaini",
    // Sustainability
    sustainability: "Uendelevu",
    log_practice: "Rekodi Mazoea",
    impact_score: "Alama ya Athari",
    soil_conservation: "Uhifadhi wa Udongo",
    water_management: "Usimamizi wa Maji",
    organic_fertilizer: "Mbolea ya Asili",
    crop_rotation: "Mzunguko wa Mazao",
    composting: "Kutengeneza Mboji",
    learn_more: "Jifunza Zaidi",
    my_practices: "Mazoea Yangu",
    no_practices: "Hakuna mazoea ya uendelevu bado",
    practice_saved: "Mazoea yamerekodiwa",
    sustainability_tips: "Vidokezo vya Uendelevu",
    // Govt/NGO
    announcements: "Matangazo",
    govt_announcement: "Serikali",
    ngo_announcement: "Shirika",
    training_opportunity: "Mafunzo",
    subsidy: "Ruzuku",
    emergency: "Dharura",
    policy_update: "Sera",
    subscribe_region: "Jiandikishe kwa Mkoa",
    filter_by_type: "Chuja kwa Aina",
    no_announcements: "Hakuna matangazo kwa sasa",
    announcement_active: "Unaotumika",
    announcement_expired: "Umekwisha",
    // Business Intelligence
    business_intelligence: "Akili ya Biashara",
    profit_forecast: "Utabiri wa Faida",
    crop_profitability: "Faida ya Mazao",
    livestock_profitability: "Faida ya Mifugo",
    market_opportunity: "Fursa za Soko",
    expense_analysis: "Uchambuzi wa Gharama",
    view_insights: "Ona Maarifa",
    trend_up: "Inakua",
    trend_down: "Inashuka",
    trend_stable: "Imara",
    bi_no_reports: "Hakuna ripoti zilizoundwa bado",
    bi_generate_first: "Tengeneza ripoti yako ya kwanza kupata maarifa",
    bi_period_30: "Siku 30 Zilizopita",
    bi_period_90: "Siku 90 Zilizopita",
    bi_period_6m: "Miezi 6 Iliyopita",
    bi_period_1y: "Mwaka Uliopita",
    eventNotes: "Maelezo",
    // Forum
    forum: "Jukwaa",
    communityForum: "Jukwaa la Jamii",
    newPost: "Chapisho Jipya",
    createTopic: "Unda Mada",
    replyToTopic: "Tuma Jibu",
    reply: "Jibu",
    replies: "majibu",
    category: "Kitengo",
    categories: "Vitengo",
    discussions: "majadiliano",
    trending: "Inayoendelea",
    recent: "Ya Hivi Karibuni",
    popular: "Maarufu",
    filterPosts: "Chuja Machapisho",
    searchPosts: "Tafuta Machapisho",
    postCreated: "Chapisho limefanikiwa!",
    replyPosted: "Jibu limetumwa!",
    startDiscussion: "Anza Mjadala",
    newTopic: "Mada Mpya",
    topicTitle: "Kichwa cha Mada",
    topicBody: "Elezea swali au mada yako...",
    addTags: "Vitambulisho (si lazima, tenganisha kwa koma)",
    submitPost: "Chapisha",
    cancelPost: "Ghairi",
    resolved: "Imetatuliwa",
    unresolved: "Weka kama Haijatatuliwa",
    markResolved: "Weka kama Imetatuliwa",
    acceptAnswer: "Kubali Jibu",
    acceptedAnswer: "Jibu Lililokubaliwa",
    recentDiscussions: "Majadiliano ya Hivi Karibuni",
    allTopics: "Mada Zote",
    mostReplies: "Majibu Mengi",
    viewTopic: "Ona Mada",
    noTopicsYet: "Hakuna mada katika kitengo hiki bado",
    noRepliesYet: "Hakuna majibu bado",
    beFirstToReply: "Kuwa wa kwanza kujibu!",
    postReply: "Tuma Jibu",
    forumWelcome: "Karibu kwenye Jukwaa la Jamii",
    forumWelcomeSub:
      "Uliza maswali, shiriki maarifa, na jifunze kutoka kwa wakulima wenzako na wataalamu.",
    // Reputation badges
    badgeHelpfulExpert: "Mtaalamu Msaada",
    badgeTrustedAdvisor: "Mshauri wa Kuaminiwa",
    badgeCommunityLeader: "Kiongozi wa Jamii",
    upvote: "Piga kura",
    upvoted: "Umepiga kura",
    communityLeaderboard: "Ubora wa Jamii",
    leaderboard: "Ubora",
    leaderboardSub: "Wanajamii wanaotoa michango bora zaidi kwenye Namwala",
    leaderboardRegion: "Mkoa",
    leaderboardRole: "Aina",
    leaderboardScore: "Alama",
    leaderboardAll: "Wote",
    leaderboardSpecialists: "Wataalamu",
    leaderboardFarmers: "Wakulima",
    leaderboardEmpty: "Hakuna matokeo. Jaribu vichujio tofauti.",
    leaderboardAllTime: "Wakati Wote",
    leaderboardThisWeek: "Wiki Hii",
    leaderboardWeeklyScore: "Alama za Wiki",
    leaderboardResetsSunday: "Inaweka upya kila Jumapili usiku wa manane UTC",
    leaderboardNoWeeklyActivity:
      "Hakuna shughuli iliyorekodi wiki hii katika mkoa huu",
    leaderboardActiveContributors: "Wachangiaji Wanaofanya Kazi",
    // Top Contributor of the Week
    topContributorTitle: "Mchangiaji Bora wa Wiki",
    topContributorEmpty: "Hakuna michango wiki hii bado — kuwa wa kwanza!",
    topContributorScore: "alama za sifa",
    // Ramani ya Milipuko ya Magonjwa
    outbreakMap: "Ramani ya Milipuko ya Magonjwa",
    reportedOutbreaks: "Milipuko Iliyoripotiwa",
    filterByType: "Chuja kwa Aina",
    filterByDate: "Chuja kwa Tarehe",
    outbreakDetails: "Maelezo ya Mlipuko",
    diseaseName: "Jina la Ugonjwa",
    affectedRegion: "Mkoa Ulioathirika",
    severity: "Ukali",
    reportOutbreak: "Ripoti Mlipuko",
    allOutbreaks: "Milipuko Yote",
    cropDisease: "Ugonjwa wa Mazao",
    livestockInfection: "Maambukizi ya Mifugo",
    pestInvasion: "Uvamizi wa Wadudu",
    drought: "Ukame",
    lowSeverity: "Chini",
    mediumSeverity: "Wastani",
    highSeverity: "Juu",
    criticalSeverity: "Hatari Sana",
    // Mnada
    liveAuctions: "Mnada wa Moja kwa Moja",
    createAuction: "Unda Mnada",
    placeBid: "Toa Zabuni",
    currentBid: "Zabuni ya Sasa",
    highestBid: "Zabuni ya Juu",
    timeRemaining: "Muda Uliobaki",
    bidHistory: "Historia ya Zabuni",
    auctionEnded: "Mnada Umekwisha",
    yourBid: "Zabuni Yako",
    minimumBid: "Zabuni ya Chini",
    startingPrice: "Bei ya Kuanzia",
    endTime: "Inaisha Saa",
    auctionWinner: "Mshindi wa Mnada",
    auctionActive: "Unaotumika",
    auctionCancelled: "Umeghairiwa",
    auctionCompleted: "Umekamilika",
    anonymousBidding: "Zabuni ya Siri",
    fixedPrice: "Bei Isiyobadilika",
    bidNow: "Toa Zabuni Sasa",
    acceptBid: "Kubali Zabuni",
    rejectBid: "Kataa Zabuni",
    auctionCreated: "Mnada umeundwa!",
    bidPlaced: "Zabuni imewekwa!",
    // Utabiri wa Mavuno
    harvestForecasting: "Utabiri wa Mavuno na Uzalishaji",
    forecastedYield: "Mavuno Yanayotarajiwa",
    confidenceScore: "Kiwango cha Uhakika",
    keyDrivers: "Sababu Kuu",
    monthlyBreakdown: "Mgawanyo wa Kila Mwezi",
    sensitivityAnalysis: "Uchambuzi wa Hisia",
    generateForecast: "Tengeneza Utabiri",
    cropYield: "Mavuno ya Mazao",
    milkProduction: "Uzalishaji wa Maziwa",
    eggProduction: "Uzalishaji wa Mayai",
    livestockWeight: "Ongezeko la Uzito wa Mifugo",
    validUntil: "Inatumika Hadi",
    forecastBasis: "Utabiri Unatokana Na",
    weatherScore: "Hali ya Hewa",
    soilScore: "Hali ya Udongo",
    feedingScore: "Ubora wa Chakula",
    historyScore: "Data ya Kihistoria",
    // Umwagiliaji
    irrigationRecommendations: "Mapendekezo ya Umwagiliaji",
    irrigationSchedule: "Ratiba ya Umwagiliaji",
    waterFrequency: "Marudio ya Kumwagilia",
    durationMinutes: "Muda (Dakika)",
    bestTimeOfDay: "Wakati Bora wa Siku",
    waterSavings: "Maji Yanayookoka",
    yieldImpact: "Athari kwa Mavuno",
    setReminder: "Weka Kumbusho",
    logUsage: "Rekodi Matumizi ya Maji",
    irrigationHistory: "Rekodi ya Umwagiliaji",
    soilMoisture: "Unyevu wa Udongo",
    weatherForecast: "Utabiri wa Hewa",
    seasonalCondition: "Hali ya Msimu",
    irrigationReasoning: "Kwa Nini Ratiba Hii",
    droneAnalysis: "Uchambuzi wa Ndege na Setilaiti",
    droneImageType: "Aina ya Picha",
    droneImageType_drone: "Picha ya Ndege",
    droneImageType_satellite: "Picha ya Setilaiti",
    droneAnalysisType: "Aina ya Uchambuzi",
    droneAnalysisType_crop_health: "Afya ya Mazao",
    droneAnalysisType_irrigation_coverage: "Umwagiliaji",
    droneAnalysisType_grazing_conditions: "Hali ya Malisho",
    droneAnalysisType_disease_spread: "Kuenea kwa Magonjwa",
    droneSubmitAnalysis: "Wasilisha kwa Uchambuzi",
    droneHealthScore: "Alama ya Afya",
    droneAiInsights: "Maarifa ya AI",
    dronePastAnalyses: "Uchambuzi wa Awali",
    droneUploadImage: "Pakia Picha",
    droneSelectFile: "Bonyeza kuchagua faili la picha",
    droneAnalyzing: "Inachambua...",
    droneNoAnalyses: "Hakuna uchambuzi bado. Pakia picha kuanza.",
    droneSeverity_critical: "Muhimu Sana",
    droneSeverity_high: "Juu",
    droneSeverity_medium: "Wastani",
    droneSeverity_low: "Chini",
    droneRecommendation: "Pendekezo",
    droneFinding: "Matokeo",
  },
};

export type TranslationKey = keyof typeof translations.en;

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggle: () => void;
  t: (key: TranslationKey) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: "en",
      setLanguage: (lang) => set({ language: lang }),
      toggle: () =>
        set((s) => ({ language: s.language === "en" ? "sw" : "en" })),
      t: (key) => {
        const lang = get().language;
        return (
          (translations[lang] as Record<string, string>)[key] ??
          (translations.en as Record<string, string>)[key] ??
          key
        );
      },
    }),
    { name: "namwala-language" },
  ),
);
